<?php
namespace App\Http\Controllers\Api\V1\Admin\Academic;
use App\Http\Controllers\Controller; use App\Models\{StudentProfile,TeacherProfile,User}; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class PeopleController extends Controller
{
 public function students(Request $r): JsonResponse { $q=User::with('studentProfile')->where('school_id',$r->user()->school_id)->where('role','student'); if($s=$r->string('search')->trim()->value()) $q->where(fn($x)=>$x->where('name','ilike',"%$s%")->orWhere('username','ilike',"%$s%")->orWhere('email','ilike',"%$s%")); return response()->json(['data'=>$q->orderBy('name')->limit(200)->get()]); }
 public function teachers(Request $r): JsonResponse { $q=User::with('teacherProfile')->where('school_id',$r->user()->school_id)->where('role','teacher'); if($s=$r->string('search')->trim()->value()) $q->where(fn($x)=>$x->where('name','ilike',"%$s%")->orWhere('username','ilike',"%$s%")->orWhere('email','ilike',"%$s%")); return response()->json(['data'=>$q->orderBy('name')->limit(200)->get()]); }
 public function storeStudent(Request $r): JsonResponse { $d=$r->validate(['name'=>'required|string|max:150','username'=>['required','string','max:80',Rule::unique('users','username')],'email'=>['required','email',Rule::unique('users','email')],'password'=>'required|string|min:10','nis'=>['required','string','max:50',Rule::unique('student_profiles','nis')],'nisn'=>'nullable|string|max:50','gender'=>'nullable|in:L,P','phone'=>'nullable|string|max:30','parent_name'=>'nullable|string|max:150','parent_phone'=>'nullable|string|max:30']); $u=DB::transaction(function()use($r,$d){$u=User::create(['school_id'=>$r->user()->school_id,'name'=>$d['name'],'username'=>$d['username'],'email'=>$d['email'],'password'=>$d['password'],'role'=>'student','status'=>'active','subtitle'=>'Siswa']);StudentProfile::create(['user_id'=>$u->id,'nis'=>$d['nis'],'nisn'=>$d['nisn']??null,'gender'=>$d['gender']??null,'phone'=>$d['phone']??null,'parent_name'=>$d['parent_name']??null,'parent_phone'=>$d['parent_phone']??null]);return $u;});return response()->json(['data'=>$u->load('studentProfile')],201); }
 public function storeTeacher(Request $r): JsonResponse { $d=$r->validate(['name'=>'required|string|max:150','username'=>['required','string','max:80',Rule::unique('users','username')],'email'=>['required','email',Rule::unique('users','email')],'password'=>'required|string|min:10','employee_no'=>'nullable|string|max:80','phone'=>'nullable|string|max:30','expertise'=>'nullable|string|max:150']); $u=DB::transaction(function()use($r,$d){$u=User::create(['school_id'=>$r->user()->school_id,'name'=>$d['name'],'username'=>$d['username'],'email'=>$d['email'],'password'=>$d['password'],'role'=>'teacher','status'=>'active','subtitle'=>'Guru']);TeacherProfile::create(['user_id'=>$u->id,'employee_no'=>$d['employee_no']??null,'phone'=>$d['phone']??null,'expertise'=>$d['expertise']??null]);return $u;});return response()->json(['data'=>$u->load('teacherProfile')],201); }
 public function updateStudent(Request $r,int $id): JsonResponse { $u=$this->person($r,$id,'student');$d=$r->validate(['name'=>'required|string|max:150','email'=>['required','email',Rule::unique('users','email')->ignore($u->id)],'nis'=>'required|string|max:50','nisn'=>'nullable|string|max:50','gender'=>'nullable|in:L,P','phone'=>'nullable|string|max:30','parent_name'=>'nullable|string|max:150','parent_phone'=>'nullable|string|max:30','status'=>'sometimes|in:active,inactive']);$u->update(['name'=>$d['name'],'email'=>$d['email'],'status'=>$d['status']??$u->status]);$u->studentProfile()->updateOrCreate(['user_id'=>$u->id],collect($d)->only(['nis','nisn','gender','phone','parent_name','parent_phone'])->all());return response()->json(['data'=>$u->fresh()->load('studentProfile')]); }
 public function updateTeacher(Request $r,int $id): JsonResponse { $u=$this->person($r,$id,'teacher');$d=$r->validate(['name'=>'required|string|max:150','email'=>['required','email',Rule::unique('users','email')->ignore($u->id)],'employee_no'=>'nullable|string|max:80','phone'=>'nullable|string|max:30','expertise'=>'nullable|string|max:150','status'=>'sometimes|in:active,inactive']);$u->update(['name'=>$d['name'],'email'=>$d['email'],'status'=>$d['status']??$u->status]);$u->teacherProfile()->updateOrCreate(['user_id'=>$u->id],collect($d)->only(['employee_no','phone','expertise'])->all());return response()->json(['data'=>$u->fresh()->load('teacherProfile')]); }
 public function destroyStudent(Request $r,int $id): JsonResponse { $this->person($r,$id,'student')->delete();return response()->json(null,204); }
 public function destroyTeacher(Request $r,int $id): JsonResponse { $this->person($r,$id,'teacher')->delete();return response()->json(null,204); }
 private function person(Request $r,int $id,string $role): User { return User::where('school_id',$r->user()->school_id)->where('role',$role)->findOrFail($id); }
}
