<?php
namespace App\Http\Controllers\Api\V1\Teacher;
use App\Http\Controllers\Controller; use App\Models\QuestionBankItem; use App\Models\Quiz; use App\Models\QuizQuestion; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class QuestionBankController extends Controller {
 private function quiz(Request $r,int $id){return Quiz::whereHas('classroom',fn($q)=>$q->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($t)=>$t->where('teacher_id',$r->user()->id)))->findOrFail($id);}
 public function index(Request $r):JsonResponse{$items=QuestionBankItem::where('school_id',$r->user()->school_id)->where('created_by',$r->user()->id)->with(['subject:id,code,name','options'])->latest()->limit(200)->get();return response()->json(['data'=>$items]);}
 public function store(Request $r):JsonResponse{$d=$this->validateData($r);$item=DB::transaction(function()use($d,$r){$i=QuestionBankItem::create(['school_id'=>$r->user()->school_id,'subject_id'=>$d['subject_id']??null,'created_by'=>$r->user()->id,'type'=>$d['type'],'question'=>$d['question'],'explanation'=>$d['explanation']??null,'default_points'=>$d['default_points']??10]);$this->syncOptions($i,$d);return $i;});return response()->json(['data'=>$item->load('options')],201);}
 public function update(Request $r,int $id):JsonResponse{$item=QuestionBankItem::where('school_id',$r->user()->school_id)->where('created_by',$r->user()->id)->findOrFail($id);$d=$this->validateData($r);DB::transaction(function()use($item,$d){$item->update(['subject_id'=>$d['subject_id']??null,'type'=>$d['type'],'question'=>$d['question'],'explanation'=>$d['explanation']??null,'default_points'=>$d['default_points']??10]);$item->options()->delete();$this->syncOptions($item,$d);});return response()->json(['data'=>$item->fresh()->load('options')]);}
 public function destroy(Request $r,int $id):JsonResponse{$item=QuestionBankItem::where('school_id',$r->user()->school_id)->where('created_by',$r->user()->id)->findOrFail($id);if(QuizQuestion::where('question_bank_item_id',$id)->exists())return response()->json(['message'=>'Soal sedang digunakan oleh quiz. Lepaskan dari quiz terlebih dahulu.'],422);$item->delete();return response()->json(null,204);}
 public function addToQuiz(Request $r,int $quizId):JsonResponse{$q=$this->quiz($r,$quizId);$d=$r->validate(['question_bank_item_id'=>'required|integer','points'=>'nullable|numeric|min:0.5|max:100']);$item=QuestionBankItem::where('school_id',$r->user()->school_id)->findOrFail($d['question_bank_item_id']);$pos=(int)$q->questions()->max('position')+1;$qq=QuizQuestion::firstOrCreate(['quiz_id'=>$q->id,'question_bank_item_id'=>$item->id],['points'=>$d['points']??$item->default_points,'position'=>$pos]);return response()->json(['data'=>$qq->load('bankItem.options')],201);}
 public function createForQuiz(Request $r,int $quizId):JsonResponse{$q=$this->quiz($r,$quizId);$d=$this->validateData($r);$qq=DB::transaction(function()use($d,$r,$q){$i=QuestionBankItem::create(['school_id'=>$r->user()->school_id,'subject_id'=>$q->classroom?->teachingAssignment?->subject_id,'created_by'=>$r->user()->id,'type'=>$d['type'],'question'=>$d['question'],'explanation'=>$d['explanation']??null,'default_points'=>$d['default_points']??10]);$this->syncOptions($i,$d);return QuizQuestion::create(['quiz_id'=>$q->id,'question_bank_item_id'=>$i->id,'points'=>$d['default_points']??10,'position'=>(int)$q->questions()->max('position')+1]);});return response()->json(['data'=>$qq->load('bankItem.options')],201);}
 public function removeFromQuiz(Request $r,int $quizId,int $quizQuestionId):JsonResponse{$q=$this->quiz($r,$quizId);$qq=$q->questions()->findOrFail($quizQuestionId);if($q->attempts()->exists())return response()->json(['message'=>'Soal tidak dapat diubah setelah siswa memulai quiz.'],422);$qq->delete();return response()->json(null,204);}
 private function validateData(Request $r):array{return $r->validate(['subject_id'=>'nullable|integer','type'=>'required|in:multiple_choice,true_false,essay','question'=>'required|string|max:10000','explanation'=>'nullable|string|max:5000','default_points'=>'nullable|numeric|min:0.5|max:100','options'=>'nullable|array|max:8','options.*.option_text'=>'required_with:options|string|max:2000','options.*.is_correct'=>'nullable|boolean']);}
 private function syncOptions(QuestionBankItem $i,array $d):void{if($i->type==='essay')return;if($i->type==='true_false'){$opts=[['option_text'=>'Benar','is_correct'=>false],['option_text'=>'Salah','is_correct'=>false]];$incoming=$d['options']??[];if(count($incoming)>=2)$opts=$incoming;foreach($opts as $k=>$o)$i->options()->create(['option_text'=>$o['option_text'],'is_correct'=>(bool)($o['is_correct']??false),'position'=>$k+1]);return;}foreach(($d['options']??[]) as $k=>$o)$i->options()->create(['option_text'=>$o['option_text'],'is_correct'=>(bool)($o['is_correct']??false),'position'=>$k+1]);}
}
