<?php
namespace App\Http\Controllers\Api\V1\Teacher;
use App\Http\Controllers\Controller; use App\Models\Quiz; use App\Models\QuizAnswer; use App\Models\QuizAttempt; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class QuizAttemptController extends Controller {
 private function quiz(Request $r,int $id){return Quiz::whereHas('classroom',fn($q)=>$q->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($t)=>$t->where('teacher_id',$r->user()->id)))->findOrFail($id);}
 private function attempt(Request $r,int $id){return QuizAttempt::whereHas('quiz.classroom',fn($q)=>$q->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($t)=>$t->where('teacher_id',$r->user()->id)))->findOrFail($id);}
 public function index(Request $r,int $quizId):JsonResponse{$q=$this->quiz($r,$quizId);$items=$q->attempts()->with('student:id,name,username,subtitle')->latest('submitted_at')->get();return response()->json(['data'=>$items]);}
 public function show(Request $r,int $id):JsonResponse{$a=$this->attempt($r,$id)->load(['student:id,name,username,subtitle','quiz.questions.bankItem.options','answers.quizQuestion.bankItem.options']);return response()->json(['data'=>$this->payload($a)]);}
 public function grade(Request $r,int $id):JsonResponse{$a=$this->attempt($r,$id)->load('quiz.questions.bankItem');$d=$r->validate(['answers'=>'required|array','answers.*.quiz_question_id'=>'required|integer','answers.*.awarded_points'=>'required|numeric|min:0','answers.*.teacher_feedback'=>'nullable|string|max:5000']);DB::transaction(function()use($a,$d,$r){$essay=0;foreach($d['answers'] as $row){$qq=$a->quiz->questions->firstWhere('id',(int)$row['quiz_question_id']);if(!$qq||$qq->bankItem->type!=='essay')continue;$pts=min((float)$row['awarded_points'],(float)$qq->points);$essay+=$pts;QuizAnswer::updateOrCreate(['quiz_attempt_id'=>$a->id,'quiz_question_id'=>$qq->id],['awarded_points'=>$pts,'teacher_feedback'=>$row['teacher_feedback']??null,'saved_at'=>now()]);}$total=(float)$a->objective_score+$essay;$a->update(['essay_score'=>$essay,'total_score'=>$total,'status'=>'graded','graded_by'=>$r->user()->id,'graded_at'=>now()]);});return response()->json(['data'=>$this->payload($a->fresh()->load(['student:id,name,username,subtitle','quiz.questions.bankItem.options','answers.quizQuestion.bankItem.options']))]);}
 public function release(Request $r,int $quizId):JsonResponse{$q=$this->quiz($r,$quizId);$q->update(['result_policy'=>'immediately']);return response()->json(['data'=>$q]);}
 private function payload(QuizAttempt $a):array{$max=(float)$a->quiz->questions->sum('points');return['id'=>$a->id,'quiz_id'=>$a->quiz_id,'attempt_no'=>$a->attempt_no,'status'=>$a->status,'started_at'=>$a->started_at,'submitted_at'=>$a->submitted_at,'auto_submitted'=>$a->auto_submitted,'objective_score'=>(float)$a->objective_score,'essay_score'=>(float)$a->essay_score,'total_score'=>$a->total_score!==null?(float)$a->total_score:null,'max_score'=>$max,'student'=>$a->student,'answers'=>$a->answers->map(function($ans){$qq=$ans->quizQuestion;$item=$qq->bankItem;return['id'=>$ans->id,'quiz_question_id'=>$qq->id,'type'=>$item->type,'question'=>$item->question,'text_answer'=>$ans->text_answer,'selected_option_id'=>$ans->selected_option_id,'boolean_answer'=>$ans->boolean_answer,'awarded_points'=>$ans->awarded_points!==null?(float)$ans->awarded_points:null,'max_points'=>(float)$qq->points,'teacher_feedback'=>$ans->teacher_feedback];})->values()];}
}
