<?php
namespace App\Http\Controllers\Api\V1\Teacher;
use App\Http\Controllers\Controller; use App\Models\Classroom; use App\Models\Quiz; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class QuizController extends Controller {
 private function owned(Request $r){return Quiz::query()->whereHas('classroom',fn($q)=>$q->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($t)=>$t->where('teacher_id',$r->user()->id)));}
 private function classOwned(Request $r,int $id){return Classroom::query()->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($q)=>$q->where('teacher_id',$r->user()->id))->findOrFail($id);}
 private function load(Quiz $q){return $q->load(['classroom.teachingAssignment.subject:id,code,name','classroom.teachingAssignment.classGroup:id,name,grade_level','questions.bankItem.options'])->loadCount('attempts');}
 public function index(Request $r):JsonResponse{$items=$this->owned($r)->with(['classroom.teachingAssignment.subject:id,code,name','classroom.teachingAssignment.classGroup:id,name'])->withCount(['questions','attempts'])->latest()->get()->map(function($q){$q->pending_review_count=$q->attempts()->where('status','submitted')->count();return $q;});return response()->json(['data'=>$items]);}
 public function store(Request $r,int $classroomId):JsonResponse{$c=$this->classOwned($r,$classroomId);$d=$r->validate(['title'=>'required|string|max:180','description'=>'nullable|string|max:5000','instructions'=>'nullable|string|max:5000','opens_at'=>'nullable|date','closes_at'=>'nullable|date|after:opens_at','time_limit_minutes'=>'nullable|integer|min:1|max:300','max_attempts'=>'nullable|integer|min:1|max:10','shuffle_questions'=>'nullable|boolean','shuffle_options'=>'nullable|boolean','passing_score'=>'nullable|numeric|min:0|max:100','result_policy'=>'nullable|in:immediately,after_close,manual']);$q=Quiz::create(array_merge($d,['classroom_id'=>$c->id,'created_by'=>$r->user()->id,'status'=>'draft']));return response()->json(['data'=>$this->load($q)],201);}
 public function show(Request $r,int $id):JsonResponse{$q=$this->owned($r)->findOrFail($id);return response()->json(['data'=>$this->load($q)]);}
 public function update(Request $r,int $id):JsonResponse{$q=$this->owned($r)->findOrFail($id);$d=$r->validate(['title'=>'sometimes|required|string|max:180','description'=>'nullable|string|max:5000','instructions'=>'nullable|string|max:5000','opens_at'=>'nullable|date','closes_at'=>'nullable|date','time_limit_minutes'=>'sometimes|integer|min:1|max:300','max_attempts'=>'sometimes|integer|min:1|max:10','shuffle_questions'=>'sometimes|boolean','shuffle_options'=>'sometimes|boolean','passing_score'=>'sometimes|numeric|min:0|max:100','result_policy'=>'sometimes|in:immediately,after_close,manual']);$q->update($d);return response()->json(['data'=>$this->load($q->fresh())]);}
 public function publish(Request $r,int $id):JsonResponse{$q=$this->owned($r)->withCount('questions')->findOrFail($id);$d=$r->validate(['published'=>'required|boolean']);if($d['published']&&$q->questions_count<1)return response()->json(['message'=>'Tambahkan minimal satu soal sebelum quiz dipublish.'],422);$q->update(['status'=>$d['published']?'published':'draft','published_at'=>$d['published']?now():null]);return response()->json(['data'=>$this->load($q->fresh())]);}
 public function destroy(Request $r,int $id):JsonResponse{$q=$this->owned($r)->findOrFail($id);if($q->attempts()->exists())return response()->json(['message'=>'Quiz yang sudah memiliki attempt tidak dapat dihapus.'],422);$q->delete();return response()->json(null,204);}
}
