import { useEffect,useMemo,useState,type FormEvent,type ReactNode } from 'react'
import { BookOpen, GraduationCap, Layers3, Plus, School, Search, Trash2, UserRoundCheck, Users, X } from 'lucide-react'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Badge, Button, Card, Input } from '@/components/ui'
import { academicApi,type AcademicYear,type ClassGroup,type Enrollment,type Major,type Overview,type Semester,type Student,type Subject,type Teacher,type TeachingAssignment } from '@/features/academic/api'

type Tab='years'|'semesters'|'majors'|'classes'|'subjects'|'teachers'|'students'|'enrollments'|'assignments'
type Entity=AcademicYear|Semester|Major|ClassGroup|Subject|Student|Teacher|Enrollment|TeachingAssignment
const tabs:[Tab,string][]=[['years','Tahun Ajaran'],['semesters','Semester'],['majors','Jurusan'],['classes','Kelas/Rombel'],['subjects','Mata Pelajaran'],['teachers','Guru'],['students','Siswa'],['enrollments','Enrollment'],['assignments','Penugasan']]

export default function AdminAcademic(){
 const [tab,setTab]=useState<Tab>('years'),[overview,setOverview]=useState<Overview|null>(null),[rows,setRows]=useState<Entity[]>([]),[years,setYears]=useState<AcademicYear[]>([]),[semesters,setSemesters]=useState<Semester[]>([]),[majors,setMajors]=useState<Major[]>([]),[classes,setClasses]=useState<ClassGroup[]>([]),[subjects,setSubjects]=useState<Subject[]>([]),[teachers,setTeachers]=useState<Teacher[]>([]),[students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[formOpen,setFormOpen]=useState(false),[editing,setEditing]=useState<Entity|null>(null),[search,setSearch]=useState(''),[error,setError]=useState('')
 async function load(){setLoading(true);setError('');try{const [ov,y,sem,m,c,sub,t,stu]=await Promise.all([academicApi.overview(),academicApi.years(),academicApi.semesters(),academicApi.majors(),academicApi.classes(),academicApi.subjects(),academicApi.teachers(),academicApi.students()]);setOverview(ov.data);setYears(y.data);setSemesters(sem.data);setMajors(m.data);setClasses(c.data);setSubjects(sub.data);setTeachers(t.data);setStudents(stu.data);const map={years:Promise.resolve(y),semesters:Promise.resolve(sem),majors:Promise.resolve(m),classes:Promise.resolve(c),subjects:Promise.resolve(sub),teachers:search?academicApi.teachers(search):Promise.resolve(t),students:search?academicApi.students(search):Promise.resolve(stu),enrollments:academicApi.enrollments(),assignments:academicApi.assignments()} as const;setRows((await map[tab]).data as Entity[])}catch(e){setError(e instanceof Error?e.message:'Gagal memuat data')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[tab])
 const title=useMemo(()=>tabs.find(x=>x[0]===tab)?.[1]??'',[tab])
 const canEdit=!['enrollments','assignments'].includes(tab)
 async function remove(id:number){if(!confirm('Hapus data ini?'))return;const resource={years:'academic-years',semesters:'semesters',majors:'majors',classes:'classes',subjects:'subjects',teachers:'teachers',students:'students',enrollments:'enrollments',assignments:'teaching-assignments'}[tab];await academicApi.remove(resource,id);await load()}
 return <AppShell title="Master Akademik"><PageHeader eyebrow="Admin • Phase 04" title="Master Data Akademik" description="Satu pusat untuk struktur akademik sekolah, pengguna, enrollment, dan penugasan mengajar." action={<Button onClick={()=>{setEditing(null);setFormOpen(true)}}><Plus size={16}/>Tambah {title}</Button>}/>
 <div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6"><Stat icon={<GraduationCap/>} n={overview?.academic_years} t="Tahun Ajaran"/><Stat icon={<School/>} n={overview?.classes} t="Rombel"/><Stat icon={<Layers3/>} n={overview?.majors} t="Jurusan"/><Stat icon={<BookOpen/>} n={overview?.subjects} t="Mapel"/><Stat icon={<UserRoundCheck/>} n={overview?.teachers} t="Guru"/><Stat icon={<Users/>} n={overview?.students} t="Siswa"/></div>
 <Card className="mt-6 overflow-hidden"><div className="border-b border-slate-200 p-3"><div className="flex gap-2 overflow-x-auto">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold ${tab===k?'bg-slate-950 text-white':'text-slate-500 hover:bg-slate-50'}`}>{l}</button>)}</div></div><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row sm:items-center"><div><h2 className="font-semibold">{title}</h2><p className="text-xs text-slate-500">{loading?'Memuat…':`${rows.length} data ditemukan`}</p></div>{(tab==='students'||tab==='teachers')&&<div className="relative ml-auto w-full sm:w-72"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void load()} className="pl-9" placeholder="Cari nama / username"/></div>}</div>{error&&<div className="m-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-slate-50 text-left text-[11px] uppercase tracking-wide text-slate-400"><tr><th className="px-5 py-3">Kode / Identitas</th><th className="px-5 py-3">Nama</th><th className="px-5 py-3">Detail</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Aksi</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} className="border-t border-slate-100"><td className="px-5 py-4 font-mono text-xs text-slate-500">{identity(tab,r)}</td><td className="px-5 py-4 font-semibold text-slate-800">{nameOf(tab,r)}</td><td className="px-5 py-4 text-xs text-slate-500">{detail(tab,r)}</td><td className="px-5 py-4"><Badge tone={r.status==='inactive'||r.is_active===false?'slate':'green'}>{r.status==='inactive'||r.is_active===false?'Nonaktif':'Aktif'}</Badge></td><td className="px-5 py-4 text-right">{canEdit&&<Button size="sm" variant="ghost" onClick={()=>{setEditing(r);setFormOpen(true)}}>Edit</Button>}<Button size="icon" variant="ghost" className="text-red-500" onClick={()=>void remove(r.id)}><Trash2 size={15}/></Button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<div className="p-10 text-center text-sm text-slate-400">Belum ada data.</div>}</div></Card>
 {formOpen&&<Editor tab={tab} entity={editing as any} years={years} semesters={semesters} majors={majors} classes={classes} subjects={subjects} teachers={teachers} students={students} onClose={()=>setFormOpen(false)} onSaved={async()=>{setFormOpen(false);await load()}}/>}
 </AppShell>}

function Stat({icon,n,t}:{icon:ReactNode,n?:number,t:string}){return <Card className="p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-blue-50 text-blue-700">{icon}</div><div><p className="text-xl font-semibold">{n??'—'}</p><p className="text-[11px] text-slate-500">{t}</p></div></div></Card>}
function identity(tab:Tab,r:any){if(tab==='students')return r.student_profile?.nis??r.username;if(tab==='teachers')return r.teacher_profile?.employee_no??r.username;if(tab==='years')return r.name;if(tab==='semesters')return `S${r.number}`;if(tab==='enrollments')return r.student?.username??`#${r.id}`;if(tab==='assignments')return r.subject?.code??`#${r.id}`;return r.code??`#${r.id}`}
function nameOf(tab:Tab,r:any){if(tab==='enrollments')return r.student?.name??'Enrollment';if(tab==='assignments')return `${r.subject?.name??'Mapel'} — ${r.teacher?.name??'Guru'}`;return r.name}
function detail(tab:Tab,r:any){if(tab==='years')return `${r.starts_on} — ${r.ends_on}`;if(tab==='semesters')return `${r.academic_year?.name??''} • ${r.starts_on} — ${r.ends_on}`;if(tab==='classes')return `${r.major?.code??'Umum'} • Kelas ${r.grade_level} • kapasitas ${r.capacity}`;if(tab==='subjects')return r.category;if(tab==='teachers')return r.teacher_profile?.expertise??r.email;if(tab==='students')return `${r.username} • ${r.email}`;if(tab==='enrollments')return `${r.class_group?.name??'Rombel'} • ${r.status}`;if(tab==='assignments')return `${r.class_group?.name??'Rombel'} • ${r.semester?.name??'Semester'} • ${r.weekly_hours} JP/minggu`;return r.description??'—'}

function Editor({tab,entity,years,semesters,majors,classes,subjects,teachers,students,onClose,onSaved}:{tab:Tab;entity:any;years:AcademicYear[];semesters:Semester[];majors:Major[];classes:ClassGroup[];subjects:Subject[];teachers:Teacher[];students:Student[];onClose:()=>void;onSaved:()=>void}){
 const [f,setF]=useState<any>(()=>defaults(tab,entity,years,semesters,majors,classes,subjects,teachers,students)),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const set=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}))
 async function submit(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const resource={years:'academic-years',semesters:'semesters',majors:'majors',classes:'classes',subjects:'subjects',teachers:'teachers',students:'students',enrollments:'enrollments',assignments:'teaching-assignments'}[tab];await academicApi.save(resource,entity?.id??null,f);onSaved()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan')}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-[80] bg-slate-950/30 backdrop-blur-sm" onMouseDown={onClose}><div className="ml-auto h-full w-full max-w-xl overflow-y-auto bg-white shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="sticky top-0 flex items-center justify-between border-b border-slate-200 bg-white p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-600">Master Akademik</p><h3 className="mt-1 text-lg font-semibold">{entity?'Edit':'Tambah'} {tabs.find(x=>x[0]===tab)?.[1]}</h3></div><Button variant="ghost" size="icon" onClick={onClose}><X size={18}/></Button></div><form onSubmit={submit} className="space-y-4 p-5">{fields(tab,f,set,years,semesters,majors,classes,subjects,teachers,students,Boolean(entity))}{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><Button type="button" variant="secondary" onClick={onClose}>Batal</Button><Button disabled={saving}>{saving?'Menyimpan…':'Simpan'}</Button></div></form></div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</label>}
const Select=({value,onChange,children,required=false}:{value:any;onChange:(v:string)=>void;children:ReactNode;required?:boolean})=><select required={required} className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-blue-500" value={value??''} onChange={e=>onChange(e.target.value)}>{children}</select>
function fields(tab:Tab,f:any,set:(k:string,v:any)=>void,years:AcademicYear[],semesters:Semester[],majors:Major[],classes:ClassGroup[],subjects:Subject[],teachers:Teacher[],students:Student[],editing:boolean){
 if(tab==='years')return <><Field label="Nama Tahun Ajaran"><Input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="2026/2027"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Mulai"><Input type="date" required value={f.starts_on} onChange={e=>set('starts_on',e.target.value)}/></Field><Field label="Selesai"><Input type="date" required value={f.ends_on} onChange={e=>set('ends_on',e.target.value)}/></Field></div><Check label="Jadikan tahun ajaran aktif" value={f.is_active} onChange={v=>set('is_active',v)}/></>
 if(tab==='semesters')return <><Field label="Tahun Ajaran"><Select required value={f.academic_year_id} onChange={v=>set('academic_year_id',Number(v))}>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Nama"><Input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="Ganjil"/></Field><Field label="Nomor"><Select required value={f.number} onChange={v=>set('number',Number(v))}><option value={1}>1</option><option value={2}>2</option></Select></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Mulai"><Input type="date" required value={f.starts_on} onChange={e=>set('starts_on',e.target.value)}/></Field><Field label="Selesai"><Input type="date" required value={f.ends_on} onChange={e=>set('ends_on',e.target.value)}/></Field></div><Check label="Jadikan semester aktif" value={f.is_active} onChange={v=>set('is_active',v)}/></>
 if(tab==='majors')return <><Field label="Kode"><Input required value={f.code} onChange={e=>set('code',e.target.value.toUpperCase())} placeholder="DKV"/></Field><Field label="Nama Jurusan"><Input required value={f.name} onChange={e=>set('name',e.target.value)}/></Field><Field label="Deskripsi"><textarea className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-blue-500" value={f.description??''} onChange={e=>set('description',e.target.value)}/></Field><Check label="Aktif" value={f.is_active} onChange={v=>set('is_active',v)}/></>
 if(tab==='subjects')return <><div className="grid gap-3 sm:grid-cols-2"><Field label="Kode"><Input required value={f.code} onChange={e=>set('code',e.target.value.toUpperCase())}/></Field><Field label="Kategori"><Select value={f.category} onChange={v=>set('category',v)}><option value="kejuruan">Kejuruan</option><option value="umum">Umum</option><option value="muatan_lokal">Muatan Lokal</option></Select></Field></div><Field label="Nama Mata Pelajaran"><Input required value={f.name} onChange={e=>set('name',e.target.value)}/></Field><Check label="Aktif" value={f.is_active} onChange={v=>set('is_active',v)}/></>
 if(tab==='classes')return <><Field label="Nama Rombel"><Input required value={f.name} onChange={e=>set('name',e.target.value)} placeholder="XI DKV 1"/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Tahun Ajaran"><Select required value={f.academic_year_id} onChange={v=>set('academic_year_id',Number(v))}>{years.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Jurusan"><Select value={f.major_id??''} onChange={v=>set('major_id',v?Number(v):null)}><option value="">Umum</option>{majors.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></Field></div><div className="grid gap-3 sm:grid-cols-2"><Field label="Tingkat"><Input type="number" min="1" max="13" required value={f.grade_level} onChange={e=>set('grade_level',Number(e.target.value))}/></Field><Field label="Kapasitas"><Input type="number" min="1" max="100" required value={f.capacity} onChange={e=>set('capacity',Number(e.target.value))}/></Field></div><Field label="Wali Kelas"><Select value={f.homeroom_teacher_id??''} onChange={v=>set('homeroom_teacher_id',v?Number(v):null)}><option value="">Belum ditentukan</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Check label="Aktif" value={f.is_active} onChange={v=>set('is_active',v)}/></>
 if(tab==='students')return <><Field label="Nama Lengkap"><Input required value={f.name} onChange={e=>set('name',e.target.value)}/></Field>{!editing&&<Field label="Username"><Input required value={f.username} onChange={e=>set('username',e.target.value)}/></Field>}<Field label="Email"><Input type="email" required value={f.email} onChange={e=>set('email',e.target.value)}/></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="NIS"><Input required value={f.nis} onChange={e=>set('nis',e.target.value)}/></Field><Field label="NISN"><Input value={f.nisn??''} onChange={e=>set('nisn',e.target.value)}/></Field></div>{!editing&&<Field label="Password awal"><Input type="password" required minLength={10} value={f.password} onChange={e=>set('password',e.target.value)} placeholder="Minimal 10 karakter"/></Field>}</>
 if(tab==='teachers')return <><Field label="Nama Lengkap"><Input required value={f.name} onChange={e=>set('name',e.target.value)}/></Field>{!editing&&<Field label="Username"><Input required value={f.username} onChange={e=>set('username',e.target.value)}/></Field>}<Field label="Email"><Input type="email" required value={f.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="NIP / NIK Pegawai"><Input value={f.employee_no??''} onChange={e=>set('employee_no',e.target.value)}/></Field><Field label="Keahlian"><Input value={f.expertise??''} onChange={e=>set('expertise',e.target.value)}/></Field>{!editing&&<Field label="Password awal"><Input type="password" required minLength={10} value={f.password} onChange={e=>set('password',e.target.value)} placeholder="Minimal 10 karakter"/></Field>}</>
 if(tab==='enrollments')return <><Field label="Siswa"><Select required value={f.student_id} onChange={v=>set('student_id',Number(v))}>{students.map(x=><option key={x.id} value={x.id}>{x.name} — {x.student_profile?.nis??x.username}</option>)}</Select></Field><Field label="Kelas / Rombel"><Select required value={f.class_group_id} onChange={v=>set('class_group_id',Number(v))}>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Tanggal Masuk"><Input type="date" value={f.enrolled_at} onChange={e=>set('enrolled_at',e.target.value)}/></Field></>
 return <><Field label="Guru"><Select required value={f.teacher_id} onChange={v=>set('teacher_id',Number(v))}>{teachers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Mata Pelajaran"><Select required value={f.subject_id} onChange={v=>set('subject_id',Number(v))}>{subjects.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Kelas"><Select required value={f.class_group_id} onChange={v=>set('class_group_id',Number(v))}>{classes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</Select></Field><Field label="Semester"><Select required value={f.semester_id} onChange={v=>set('semester_id',Number(v))}>{semesters.map(x=><option key={x.id} value={x.id}>{x.academic_year?.name} • {x.name}</option>)}</Select></Field></div><Field label="JP per Minggu"><Input type="number" min="1" max="20" required value={f.weekly_hours} onChange={e=>set('weekly_hours',Number(e.target.value))}/></Field></>
}
function Check({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)} className="h-4 w-4"/>{label}</label>}
function defaults(tab:Tab,e:any,years:AcademicYear[],semesters:Semester[],majors:Major[],classes:ClassGroup[],subjects:Subject[],teachers:Teacher[],students:Student[]){if(e){if(tab==='students')return{name:e.name,email:e.email,nis:e.student_profile?.nis??'',nisn:e.student_profile?.nisn??'',gender:e.student_profile?.gender??'',phone:e.student_profile?.phone??'',parent_name:e.student_profile?.parent_name??'',parent_phone:e.student_profile?.parent_phone??'',status:e.status};if(tab==='teachers')return{name:e.name,email:e.email,employee_no:e.teacher_profile?.employee_no??'',phone:e.teacher_profile?.phone??'',expertise:e.teacher_profile?.expertise??'',status:e.status};return{...e}}
 if(tab==='years')return{name:'2026/2027',starts_on:'2026-07-13',ends_on:'2027-06-25',is_active:false};if(tab==='semesters')return{academic_year_id:years[0]?.id??'',name:'Ganjil',number:1,starts_on:'2026-07-13',ends_on:'2026-12-18',is_active:false};if(tab==='majors')return{code:'',name:'',description:'',is_active:true};if(tab==='subjects')return{code:'',name:'',category:'kejuruan',description:'',is_active:true};if(tab==='classes')return{name:'',academic_year_id:years[0]?.id??'',major_id:majors[0]?.id??null,homeroom_teacher_id:null,grade_level:11,capacity:36,is_active:true};if(tab==='students')return{name:'',username:'',email:'',password:'',nis:'',nisn:'',gender:'L',phone:'',parent_name:'',parent_phone:''};if(tab==='teachers')return{name:'',username:'',email:'',password:'',employee_no:'',phone:'',expertise:''};if(tab==='enrollments')return{student_id:students[0]?.id??'',class_group_id:classes[0]?.id??'',enrolled_at:'2026-07-13',status:'active'};return{teacher_id:teachers[0]?.id??'',subject_id:subjects[0]?.id??'',class_group_id:classes[0]?.id??'',semester_id:semesters[0]?.id??'',weekly_hours:2}}
