import { ChevronLeft, ChevronRight, Plus } from 'lucide-react'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Button, Card } from '@/components/ui'

const days=['Sen','Sel','Rab','Kam','Jum','Sab','Min']
const cells=Array.from({length:35},(_,i)=>i+1)
const events:Record<number,string[]>={3:['Quiz Tipografi'],5:['Tugas DKV'],10:['Fotografi Digital','DKV'],12:['Deadline Poster'],14:['Foto Produk'],18:['Grid Typography'],24:['Presentasi']}
export default function Calendar(){return <AppShell title="Kalender Belajar"><PageHeader eyebrow="Academic planner" title="Kalender Belajar" description="Lihat kelas, deadline, quiz, dan agenda belajar dalam satu timeline." action={<Button><Plus size={16}/>Tambah agenda</Button>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_320px]"><Card className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">August 2026</p><h3 className="mt-1 text-base font-semibold">Agustus 2026</h3></div><div className="flex gap-2"><Button variant="secondary" size="icon"><ChevronLeft size={16}/></Button><Button variant="secondary" size="sm">Hari ini</Button><Button variant="secondary" size="icon"><ChevronRight size={16}/></Button></div></div><div className="scrollbar-thin overflow-x-auto"><div className="min-w-[760px]"><div className="grid grid-cols-7 border-b border-slate-100 bg-slate-50">{days.map(d=><div key={d} className="border-r border-slate-100 px-3 py-3 text-center text-[9px] font-bold uppercase tracking-[.12em] text-slate-400 last:border-r-0">{d}</div>)}</div><div className="grid grid-cols-7">{cells.map(n=><div key={n} className={`min-h-[112px] border-b border-r border-slate-100 p-2.5 last:border-r-0 ${n===10?'bg-blue-50/40':''}`}><span className={`grid h-7 w-7 place-items-center rounded-lg text-[10px] font-semibold ${n===10?'bg-blue-600 text-white':'text-slate-500'}`}>{n}</span><div className="mt-1 space-y-1">{events[n]?.map((e,i)=><div key={e} className={`truncate rounded-md border-l-2 px-2 py-1.5 text-[9px] font-semibold ${i===0?'border-blue-600 bg-blue-50 text-blue-800':'border-slate-500 bg-slate-100 text-slate-700'}`}>{e}</div>)}</div></div>)}</div></div></div></Card><aside><Card className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Upcoming</p><h3 className="mt-1 text-base font-semibold">Agenda terdekat</h3><div className="mt-4 divide-y divide-slate-100">{[['Besok • 07:00','Fotografi Digital','Lab DKV'],['12 Agu • 23.59','Deadline Poster','EduNova'],['14 Agu • 20.00','Foto Produk Manual','EduNova'],['18 Agu • 23.59','Grid Typography','EduNova']].map(([date,title,meta])=><div key={title} className="py-4"><p className="text-[10px] font-semibold text-blue-700">{date}</p><b className="mt-1 block text-sm text-slate-800">{title}</b><span className="mt-1 block text-xs text-slate-400">{meta}</span></div>)}</div></Card></aside></div></AppShell>}
