import { useEffect, useState } from 'react'
import { Clock3, FileQuestion, Play, Trophy } from 'lucide-react'
import { Link } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Badge, Button, Card } from '@/components/ui'
import { quizApi, type Quiz } from '@/features/quiz/api'
export default function StudentQuizzes(){const[items,setItems]=useState<Quiz[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{quizApi.student.list().then(r=>setItems(r.data)).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat quiz.')).finally(()=>setLoading(false))},[]);return <AppShell title="Quiz & Ujian"><PageHeader eyebrow="Assessment" title="Quiz & Ujian" description="Kerjakan evaluasi sesuai jadwal. Jawaban akan disimpan otomatis selama ujian berlangsung."/>{error&&<div className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3].map(i=><Card key={i} className="h-56 animate-pulse bg-slate-100"/>):items.map(q=>{const closed=q.closes_at&&new Date(q.closes_at)<new Date();return <Card key={q.id} className="p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><FileQuestion size={19}/></div><Badge tone={closed?'red':'green'}>{closed?'Ditutup':'Tersedia'}</Badge></div><h3 className="mt-5 font-semibold">{q.title}</h3><p className="mt-1 text-xs text-slate-500">{q.classroom?.teaching_assignment?.subject?.name} • {q.classroom?.teaching_assignment?.teacher?.name}</p><div className="mt-5 grid grid-cols-3 gap-2"><Mini icon={<FileQuestion/>} label="Soal" value={String(q.questions_count??0)}/><Mini icon={<Clock3/>} label="Waktu" value={`${q.time_limit_minutes}m`}/><Mini icon={<Trophy/>} label="Terbaik" value={q.best_score!=null?String(q.best_score):'—'}/></div><p className="mt-4 text-xs text-slate-500">Attempt {q.attempts_used??0}/{q.max_attempts}{q.closes_at?` • Tutup ${fmt(q.closes_at)}`:''}</p><Link to={q.active_attempt_id?`/quiz/attempts/${q.active_attempt_id}`:`/quiz/${q.id}`}><Button className="mt-4 w-full" variant="dark" disabled={!!closed}><Play size={15}/>{q.active_attempt_id?'Lanjutkan attempt':'Buka quiz'}</Button></Link></Card>})}</div></AppShell>}
function Mini({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-2.5"><div className="text-slate-400">{icon}</div><b className="mt-2 block text-sm">{value}</b><span className="text-[9px] text-slate-500">{label}</span></div>}function fmt(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
