import { useEffect, useState } from 'react'
import { ArrowLeft, CheckCircle2, ExternalLink, FileText, Save, Send, Trash2, UploadCloud } from 'lucide-react'
import { Link, useParams } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { Badge, Button, Card } from '@/components/ui'
import { assignmentApi, type Assignment } from '@/features/assignment/api'

export default function StudentAssignmentDetail(){
 const{id}=useParams();const aid=Number(id);const[item,setItem]=useState<Assignment|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[text,setText]=useState(''),[link,setLink]=useState(''),[files,setFiles]=useState<File[]>([])
 async function load(){setLoading(true);setError('');try{const r=await assignmentApi.student.get(aid);setItem(r.data);setText(r.data.student_submission?.text_answer??'');setLink(r.data.student_submission?.link_url??'')}catch(e){setError(e instanceof Error?e.message:'Gagal memuat tugas.')}finally{setLoading(false)}}
 useEffect(()=>{if(aid)void load()},[aid])
 async function save(action:'draft'|'submit'){setSaving(true);setError('');setMessage('');try{await assignmentApi.student.save(aid,{action,text_answer:text,link_url:link,files});setFiles([]);setMessage(action==='submit'?'Tugas berhasil dikirim.':'Draft berhasil disimpan.');await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan submission.')}finally{setSaving(false)}}
 async function removeFile(fileId:number){if(!confirm('Hapus file ini?'))return;try{await assignmentApi.student.removeFile(fileId);await load()}catch(e){setError(e instanceof Error?e.message:'File tidak dapat dihapus.')}}
 if(loading)return <AppShell title="Detail Tugas"><Card className="h-72 animate-pulse bg-slate-100"/></AppShell>
 if(!item)return <AppShell title="Detail Tugas"><Card className="p-6">Tugas tidak ditemukan.</Card></AppShell>
 const submission=item.student_submission;const locked=submission?.status==='graded'||submission?.status==='returned'||(submission?.status==='submitted'&&!item.allow_resubmit)||(submission?.status==='late')
 const criteria=item.rubric_criteria??item.rubricCriteria??[]
 return <AppShell title="Detail Tugas"><div className="mb-5"><Link to="/assignments" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/>Tugas Saya</Link></div>{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{message&&<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{message}</div>}
 <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><Card className="overflow-hidden p-0"><div className="bg-[#0D1B36] p-6 text-white"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">{item.classroom?.teaching_assignment?.subject?.name} • {item.classroom?.teaching_assignment?.class_group?.name}</p><h2 className="mt-2 text-2xl font-semibold">{item.title}</h2><div className="mt-4 flex flex-wrap gap-2"><Badge tone={item.is_overdue?'red':'amber'}>{item.due_at?`Deadline ${formatDate(item.due_at)}`:'Tanpa deadline'}</Badge>{submission&&<Badge tone={tone(submission.status)}>{submission.status}</Badge>}</div></div></Card>
 <Card className="p-6"><h3 className="text-sm font-semibold">Instruksi</h3><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.instructions||'Tidak ada instruksi tambahan.'}</p>{(item.attachments??[]).length>0&&<div className="mt-5 border-t border-slate-100 pt-5"><p className="mb-2 text-xs font-semibold text-slate-500">Lampiran guru</p>{item.attachments?.map(f=><a key={f.id} href={f.file_url??'#'} target="_blank" rel="noreferrer" className="mb-2 flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50"><FileText size={16} className="text-blue-600"/><span className="truncate">{f.original_name}</span></a>)}</div>}</Card>
 {criteria.length>0&&<Card className="p-6"><h3 className="text-sm font-semibold">Rubrik penilaian</h3><div className="mt-4 space-y-2">{criteria.map(c=><div key={c.id} className="flex items-start justify-between gap-4 rounded-xl bg-slate-50 p-4"><div><p className="text-xs font-semibold">{c.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{c.description}</p></div><b className="text-sm">{Number(c.max_points)} poin</b></div>)}</div></Card>}
 </div><div className="space-y-6"><Card className="p-6"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Submission Workspace</h3>{submission&&<Badge tone={tone(submission.status)}>{submission.status}</Badge>}</div>
 {locked?<div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold">Submission sudah terkunci.</p><p className="mt-1 text-xs leading-5 text-slate-500">{submission?.status==='returned'?'Nilai dan feedback sudah dikembalikan oleh guru.':'Perubahan tidak tersedia untuk status submission saat ini.'}</p></div>:<><>{item.allow_text&&<label className="mt-4 block"><span className="text-xs font-semibold text-slate-500">Jawaban teks</span><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-2 min-h-36 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Tulis jawaban atau refleksi..."/></label>}</>{item.allow_link&&<label className="mt-4 block"><span className="text-xs font-semibold text-slate-500">Link</span><div className="relative mt-2"><ExternalLink size={15} className="absolute left-3 top-3 text-slate-400"/><input value={link} onChange={e=>setLink(e.target.value)} className="h-10 w-full rounded-xl border border-slate-200 pl-9 pr-3 text-sm" placeholder="https://..."/></div></label>}{item.allow_file&&<label className="mt-4 block cursor-pointer rounded-2xl border border-dashed border-blue-200 bg-blue-50/40 p-5 text-center"><input type="file" multiple className="hidden" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><UploadCloud className="mx-auto text-blue-600" size={22}/><b className="mt-2 block text-xs">Pilih file submission</b><p className="mt-1 text-[10px] text-slate-500">Maks. 5 file • {item.max_file_mb} MB per file</p>{files.length>0&&<p className="mt-2 text-xs font-semibold text-blue-700">{files.length} file dipilih</p>}</label>}<div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" disabled={saving||Boolean(item.is_overdue)||Boolean(submission&&['submitted','late'].includes(submission.status))} onClick={()=>save('draft')}><Save size={15}/>Simpan draft</Button><Button disabled={saving} onClick={()=>save('submit')}><Send size={15}/>{submission&&['submitted','late'].includes(submission.status)?'Resubmit':'Kirim tugas'}</Button></div></>}
 {(submission?.files??[]).length>0&&<div className="mt-5 border-t border-slate-100 pt-4"><p className="mb-2 text-xs font-semibold text-slate-500">File tersimpan</p>{submission?.files?.map(f=><div key={f.id} className="mb-2 flex items-center justify-between rounded-xl bg-slate-50 p-3"><a href={f.file_url??'#'} target="_blank" rel="noreferrer" className="min-w-0 truncate text-xs font-semibold text-blue-700">{f.original_name}</a>{!locked&&<button onClick={()=>removeFile(f.id)} className="text-red-500"><Trash2 size={14}/></button>}</div>)}</div>}
 </Card>
 {submission&&['graded','returned'].includes(submission.status)&&<Card className="p-6"><div className="flex items-center gap-2 text-emerald-700"><CheckCircle2 size={18}/><h3 className="text-sm font-semibold">Hasil penilaian</h3></div><div className="mt-4 rounded-xl bg-emerald-50 p-4"><p className="text-[10px] font-bold uppercase tracking-[.12em] text-emerald-600">Nilai</p><b className="mt-1 block text-3xl text-emerald-900">{Number(submission.score??0)}<span className="text-base font-medium text-emerald-600">/{Number(item.max_score)}</span></b></div><p className="mt-4 whitespace-pre-wrap text-sm leading-6 text-slate-600">{submission.feedback||'Belum ada feedback tertulis.'}</p></Card>}
 </div></div></AppShell>
}
function formatDate(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
function tone(s:string):'blue'|'green'|'amber'|'red'|'slate'{return s==='late'?'red':s==='submitted'?'amber':s==='returned'?'green':s==='graded'?'blue':'slate'}
