import { useEffect, useState } from 'react'
import { Camera, CheckCircle2, Clock3, LocateFixed, MapPin, QrCode, ShieldCheck } from 'lucide-react'
import AppShell from '@/components/layout/AppShell'
import { Button, Card } from '@/components/ui'
import { apiRequest, ApiError } from '@/lib/api/client'
import { QRCodeScanner } from '@/components/shared/QRCodeScanner'

type Session={id:number;title:string;opens_at:string;late_after?:string|null;closes_at:string;require_gps:boolean;radius_meters:number;require_dynamic_qr:boolean;require_selfie:boolean;my_record?:{status:string;checked_in_at?:string}}
type Record={id:number;status:string;method:string;checked_in_at?:string;session?:{title:string;classroom?:{title:string;teaching_assignment?:{subject?:{name:string}}}}}
type Data<T>={data:T}
export default function StudentAttendance(){
 const [scannerOpen,setScannerOpen]=useState(false)
 const [active,setActive]=useState<Session[]>([]),[history,setHistory]=useState<Record[]>([]),[selected,setSelected]=useState<Session|null>(null),[token,setToken]=useState(''),[location,setLocation]=useState<{lat:number;lng:number;accuracy:number}|null>(null),[selfie,setSelfie]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 async function load(){const [a,h]=await Promise.all([apiRequest<Data<Session[]>>('/student/attendance/active'),apiRequest<Data<Record[]>>('/student/attendance/history')]);setActive(a.data);setHistory(h.data);if(!selected&&a.data[0])setSelected(a.data[0])}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 function getLocation(){setError('');navigator.geolocation.getCurrentPosition(p=>setLocation({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),()=>setError('Lokasi tidak tersedia. Izinkan akses lokasi pada browser.'),{enableHighAccuracy:true,timeout:12000})}
 async function checkIn(){if(!selected)return;setBusy(true);setError('');setMessage('');try{const fd=new FormData();if(token)fd.append('qr_token',token);if(location){fd.append('latitude',String(location.lat));fd.append('longitude',String(location.lng));fd.append('gps_accuracy',String(location.accuracy))}if(selfie)fd.append('selfie',selfie);const r=await apiRequest<Data<{status:string}>>(`/student/attendance/sessions/${selected.id}/check-in`,{method:'POST',body:fd});setMessage(`Absensi berhasil: ${r.data.status==='late'?'Terlambat':'Hadir'}`);setToken('');setSelfie(null);await load()}catch(e){setError(e instanceof ApiError?e.message:'Check-in gagal')}finally{setBusy(false)}}
 return <AppShell title="Absensi">
  <div className="grid gap-6 xl:grid-cols-[1fr_360px]">
   <div className="space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Attendance</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">Sesi aktif</h2><p className="mt-1 text-sm text-slate-500">Check-in sesuai kebijakan yang ditetapkan guru.</p></div>
    {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700"><CheckCircle2 size={17} className="mr-2 inline"/>{message}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
    {!active.length?<Card className="p-10 text-center"><ShieldCheck className="mx-auto text-slate-300" size={40}/><h3 className="mt-3 font-semibold">Tidak ada sesi aktif</h3><p className="mt-1 text-sm text-slate-500">Sesi absensi akan muncul ketika guru membukanya.</p></Card>:<div className="grid gap-4 md:grid-cols-2">{active.map(s=><button key={s.id} onClick={()=>{setSelected(s);setToken('');setSelfie(null);setLocation(null)}} className={`text-left ${selected?.id===s.id?'ring-2 ring-blue-500 rounded-[18px]':''}`}><Card className="h-full p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><Clock3 size={18}/></div>{s.my_record&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">{s.my_record.status.toUpperCase()}</span>}</div><h3 className="mt-4 font-semibold">{s.title}</h3><p className="mt-1 text-xs text-slate-500">Tutup {new Date(s.closes_at).toLocaleTimeString('id-ID')}</p><div className="mt-4 flex flex-wrap gap-1.5 text-[10px] font-semibold text-slate-500">{s.require_dynamic_qr&&<span className="rounded-md bg-slate-100 px-2 py-1">QR</span>}{s.require_gps&&<span className="rounded-md bg-slate-100 px-2 py-1">GPS {s.radius_meters}m</span>}{s.require_selfie&&<span className="rounded-md bg-slate-100 px-2 py-1">SELFIE</span>}</div></Card></button>)}</div>}
    <div><h3 className="mb-3 font-semibold">Riwayat kehadiran</h3><Card className="overflow-hidden p-0">{history.length?history.map(r=><div key={r.id} className="flex items-center justify-between gap-4 border-b border-slate-100 px-5 py-4 last:border-0"><div><b className="text-sm">{r.session?.title}</b><p className="mt-1 text-xs text-slate-500">{r.session?.classroom?.title} • {r.checked_in_at?new Date(r.checked_in_at).toLocaleString('id-ID'):'-'}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${r.status==='present'?'bg-emerald-50 text-emerald-700':r.status==='late'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{r.status.toUpperCase()}</span></div>):<div className="p-8 text-center text-sm text-slate-500">Belum ada riwayat.</div>}</Card></div>
   </div>
   <div>{selected&&<Card className="sticky top-28 p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">Check-in</p><h3 className="mt-1 text-lg font-semibold">{selected.title}</h3>{selected.my_record?<div className="mt-5 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700"><CheckCircle2 size={18} className="mr-2 inline"/>Anda sudah tercatat <b>{selected.my_record.status}</b>.</div>:<div className="mt-5 space-y-4">
    {selected.require_dynamic_qr&&<div><label className="block"><span className="text-xs font-semibold text-slate-600"><QrCode size={14} className="mr-1 inline"/> Dynamic QR / code</span><input value={token} onChange={e=>setToken(e.target.value.toUpperCase())} placeholder="Scan QR atau masukkan kode" className="mt-2 w-full rounded-xl border border-slate-200 px-3 py-3 font-mono text-sm uppercase tracking-widest"/></label><Button variant="secondary" className="mt-2 w-full" onClick={()=>setScannerOpen(true)}><QrCode size={16}/> Scan QR dengan Kamera</Button></div>}
    {selected.require_gps&&<div><Button variant="secondary" className="w-full" onClick={getLocation}><LocateFixed size={16}/> Ambil Lokasi Saya</Button>{location&&<div className="mt-2 rounded-xl bg-blue-50 p-3 text-xs text-blue-700"><MapPin size={14} className="mr-1 inline"/> Lokasi siap • akurasi ±{Math.round(location.accuracy)} m</div>}</div>}
    {selected.require_selfie&&<label className="block rounded-xl border border-dashed border-slate-300 p-4 text-center"><Camera className="mx-auto text-slate-400" size={28}/><span className="mt-2 block text-sm font-semibold">Ambil selfie</span><span className="text-xs text-slate-400">Kamera depan disarankan</span><input type="file" accept="image/*" capture="user" className="mt-3 block w-full text-xs" onChange={e=>setSelfie(e.target.files?.[0]??null)}/></label>}
    <Button className="w-full" disabled={busy||(selected.require_dynamic_qr&&!token)||(selected.require_gps&&!location)||(selected.require_selfie&&!selfie)} onClick={checkIn}>{busy?'Memverifikasi...':'Kirim Absensi'}</Button>
   </div>}</Card>}</div>
  </div>
  <QRCodeScanner open={scannerOpen} onClose={()=>setScannerOpen(false)} onScan={value=>setToken(value)}/>
 </AppShell>
}
