import type { ReactNode } from 'react'
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, MoreHorizontal, Play, Target, TrendingUp } from 'lucide-react'
import { Link } from 'react-router'
import { motion } from 'motion/react'
import AppShell from '@/components/layout/AppShell'
import { CourseCard } from '@/components/shared/CourseCard'
import { PageHeader } from '@/components/shared/PageHeader'
import { SectionTitle } from '@/components/shared/SectionTitle'
import { Badge, Button, Card, Progress } from '@/components/ui'
import { courses, schedule, tasks } from '@/data/mock'

export default function StudentDashboard(){ return <AppShell title="Ringkasan Belajar">
  <PageHeader eyebrow="Senin, 10 Agustus 2026" title="Selamat malam, Andi." description="Ada dua agenda kelas dan satu tugas prioritas. Mulai dari aktivitas yang paling dekat dengan targetmu hari ini." action={<Link to="/calendar"><Button variant="dark"><CalendarDays size={16}/>Lihat jadwal</Button></Link>}/>

  <section className="grid gap-5 xl:grid-cols-[minmax(0,1.65fr)_minmax(300px,.7fr)]">
    <motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="relative overflow-hidden rounded-[22px] bg-[#0D1B36] p-6 text-white shadow-[0_22px_55px_rgba(15,23,42,.13)] sm:p-7 dashboard-grid"><div className="absolute right-0 top-0 h-full w-[42%] bg-gradient-to-l from-blue-600/25 to-transparent"/><div className="relative grid h-full gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><div className="flex flex-wrap items-center gap-2"><Badge tone="blue" className="border-white/10 bg-white/[.08] text-blue-100">Lanjutkan belajar</Badge><span className="text-xs text-slate-400">Chapter 04 • 12 menit</span></div><p className="mt-6 text-xs font-semibold uppercase tracking-[.14em] text-blue-300">Fotografi Digital</p><h3 className="mt-2 max-w-xl text-2xl font-semibold tracking-[-.035em] sm:text-[30px]">Memahami Exposure Triangle</h3><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Lanjut dari bagian terakhir: hubungan aperture, shutter speed, dan ISO dalam situasi pencahayaan nyata.</p><div className="mt-6 flex flex-wrap items-center gap-3"><Link to="/material"><Button className="border-white bg-white text-slate-950 hover:border-slate-100 hover:bg-slate-100"><Play size={16} fill="currentColor"/>Lanjutkan materi</Button></Link><span className="text-xs text-slate-400">72% course selesai</span></div></div><div className="hidden h-36 w-36 place-items-center rounded-full border border-white/10 bg-white/[.04] md:grid"><div className="grid h-24 w-24 place-items-center rounded-full border-[7px] border-blue-500 border-l-white/10 text-center"><div><strong className="text-2xl">72%</strong><span className="block text-[9px] uppercase tracking-wider text-slate-400">Progress</span></div></div></div></div></motion.div>

    <Card className="p-0"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">Hari ini</p><h3 className="mt-1 text-base font-semibold">Agenda belajar</h3></div><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-50"><MoreHorizontal size={18}/></button></div><div className="divide-y divide-slate-100">{schedule.map((item,i)=><div className="flex gap-4 px-5 py-4" key={item.time}><div className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${i===0?'bg-blue-600':'bg-slate-300'}`}/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold text-slate-800">{item.title}</p><span className="text-xs font-medium text-slate-400">{item.time}</span></div><p className="mt-1 text-xs text-slate-500">{item.meta}</p></div></div>)}</div></Card>
  </section>

  <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<BookOpen/>} label="Kelas aktif" value="6" note="Semester ini"/><Metric icon={<CheckCircle2/>} label="Tugas selesai" value="18" note="3 minggu terakhir"/><Metric icon={<TrendingUp/>} label="Rata-rata nilai" value="88.4" note="Naik 3,2 poin" positive/><Metric icon={<Clock3/>} label="Waktu belajar" value="6j 40m" note="Minggu ini"/></section>

  <section className="mt-8"><SectionTitle eyebrow="Learning space" title="Kelas saya" action={<Link to="/courses" className="inline-flex items-center gap-1 text-sm font-semibold text-blue-700">Semua kelas <ArrowRight size={15}/></Link>}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{courses.slice(0,3).map(c=><CourseCard key={c.id} course={c}/>)}</div></section>

  <section className="mt-8 grid gap-5 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,.6fr)]"><Card className="p-5"><SectionTitle eyebrow="Prioritas" title="Tugas terdekat" action={<Link to="/assignments" className="text-sm font-semibold text-blue-700">Lihat semua</Link>}/><div className="space-y-1">{tasks.map((t,i)=><div key={t.id} className="grid gap-3 rounded-xl px-2 py-3 transition hover:bg-slate-50 sm:grid-cols-[auto_1fr_auto] sm:items-center"><div className="grid h-10 w-10 place-items-center rounded-xl bg-slate-100 text-sm font-semibold text-slate-600">0{i+1}</div><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800">{t.title}</p><p className="mt-1 truncate text-xs text-slate-500">{t.course}</p></div><div className="flex items-center gap-3"><span className="text-xs font-medium text-slate-500">{t.due}</span><Badge tone={i===0?'amber':'slate'}>{t.status}</Badge></div></div>)}</div></Card><Card className="p-5"><div className="flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-700"><Target size={19}/></div><Badge tone="green">On track</Badge></div><h3 className="mt-5 text-lg font-semibold">Target minggu ini</h3><p className="mt-1 text-sm leading-6 text-slate-500">Selesaikan 4 aktivitas belajar sebelum Minggu.</p><div className="mt-5 flex items-end justify-between"><div><span className="text-3xl font-bold tracking-tight">3</span><span className="text-sm text-slate-400"> / 4 selesai</span></div><span className="text-xs font-semibold text-blue-700">75%</span></div><Progress value={75} className="mt-3 h-2"/></Card></section>
</AppShell> }

function Metric({icon,label,value,note,positive}:{icon:ReactNode,label:string,value:string,note:string,positive?:boolean}){return <Card className="flex items-start gap-4 p-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl border border-slate-200 bg-slate-50 text-slate-600">{icon}</div><div className="min-w-0"><p className="text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-xl font-semibold tracking-tight text-slate-950">{value}</p><p className={`mt-1 text-[11px] ${positive?'text-emerald-600':'text-slate-400'}`}>{note}</p></div></Card>}
