import { useEffect, useMemo, useState } from 'react'
import { CalendarClock, CheckCircle2, ClipboardList, Clock3, FileCheck2 } from 'lucide-react'
import { Link } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Badge, Button, Card } from '@/components/ui'
import { assignmentApi, type Assignment } from '@/features/assignment/api'

export default function StudentAssignments(){const[items,setItems]=useState<Assignment[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState('all');useEffect(()=>{assignmentApi.student.list().then(r=>setItems(r.data)).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat tugas.')).finally(()=>setLoading(false))},[]);const visible=useMemo(()=>items.filter(a=>filter==='all'||statusOf(a)===filter),[items,filter]);return <AppShell title="Tugas & Deadline"><PageHeader eyebrow="Assignment Center • Phase 06" title="Tugas Saya" description="Prioritaskan deadline, kirim pekerjaan, dan pantau feedback guru."/>{error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="mb-6 flex flex-wrap gap-2">{[['all','Semua'],['pending','Perlu dikerjakan'],['submitted','Terkirim'],['returned','Sudah dinilai']] .map(([k,l])=><button key={k} onClick={()=>setFilter(k)} className={`rounded-xl border px-3 py-2 text-xs font-semibold ${filter===k?'border-blue-600 bg-blue-600 text-white':'border-slate-200 bg-white text-slate-600'}`}>{l}</button>)}</div><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3].map(i=><Card key={i} className="h-56 animate-pulse bg-slate-100"/>):visible.map(a=>{const s=a.student_submission;const st=statusOf(a);return <Card key={a.id} className="p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><ClipboardList size={18}/></div><Badge tone={tone(st)}>{label(st)}</Badge></div><h3 className="mt-5 text-base font-semibold">{a.title}</h3><p className="mt-1 text-xs text-slate-500">{a.classroom?.teaching_assignment?.subject?.name} • {a.classroom?.teaching_assignment?.class_group?.name}</p><div className="mt-5 flex items-center gap-2 text-xs text-slate-500"><CalendarClock size={14}/>{a.due_at?formatDate(a.due_at):'Tanpa deadline'}</div>{s?.score!=null&&<div className="mt-4 rounded-xl bg-emerald-50 p-3"><p className="text-[10px] font-semibold uppercase text-emerald-600">Nilai</p><b className="mt-1 block text-xl text-emerald-800">{Number(s.score)}/{Number(a.max_score)}</b></div>}<Link to={`/assignments/${a.id}`}><Button variant={st==='pending'||st==='overdue'?'primary':'secondary'} className="mt-5 w-full">{st==='pending'||st==='overdue'?'Kerjakan tugas':'Buka detail'}</Button></Link></Card>})}</div>{!loading&&!visible.length&&<Card className="border-dashed p-8 text-center shadow-none"><CheckCircle2 className="mx-auto text-emerald-500"/><p className="mt-3 text-sm font-semibold">Tidak ada tugas pada kategori ini.</p></Card>}</AppShell>}
function statusOf(a:Assignment){const s=a.student_submission?.status;if(s==='returned')return'returned';if(s==='graded')return'graded';if(s==='submitted'||s==='late')return'submitted';if(a.is_overdue)return'overdue';return'pending'}
function label(s:string){return s==='returned'?'Dinilai':s==='graded'?'Dinilai':s==='submitted'?'Terkirim':s==='overdue'?'Lewat deadline':'Pending'}
function tone(s:string):'blue'|'green'|'amber'|'red'|'slate'{return s==='returned'||s==='graded'?'green':s==='submitted'?'blue':s==='overdue'?'red':'amber'}
function formatDate(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
