import { useEffect, useMemo, useState } from 'react'
import { useParams } from 'react-router'
import { AlertTriangle, CheckCircle2, RefreshCw, Save, Send, SlidersHorizontal, UserRound, XCircle } from 'lucide-react'
import AppShell from '@/components/layout/AppShell'
import { Badge, Button, Card, Input, Progress } from '@/components/ui'
import { gradeApi, type Gradebook, type GradeStudent } from '@/features/grades/api'

const fmt=(n:number|null|undefined)=>n==null?'—':n.toFixed(1)
export default function TeacherGradebookDetail(){
 const {classroomId}=useParams(); const id=Number(classroomId)
 const [data,setData]=useState<Gradebook|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState('')
 const [aw,setAw]=useState(60); const [qw,setQw]=useState(40); const [passing,setPassing]=useState(75); const [missing,setMissing]=useState(false)
 const load=()=>{setLoading(true);gradeApi.teacher.get(id).then(r=>{setData(r.data);setAw(r.data.settings.assignment_weight);setQw(r.data.settings.quiz_weight);setPassing(r.data.settings.passing_grade);setMissing(r.data.settings.missing_as_zero)}).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat gradebook')).finally(()=>setLoading(false))}
 useEffect(load,[id])
 const save=async()=>{setBusy(true);setError('');try{await gradeApi.teacher.settings(id,{assignment_weight:aw,quiz_weight:qw,passing_grade:passing,missing_as_zero:missing});load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan')}finally{setBusy(false)}}
 const publish=async()=>{setBusy(true);try{const r=await gradeApi.teacher.publish(id);setData(r.data)}catch(e){setError(e instanceof Error?e.message:'Gagal publish')}finally{setBusy(false)}}
 const unpublish=async()=>{setBusy(true);try{const r=await gradeApi.teacher.unpublish(id);setData(r.data)}catch(e){setError(e instanceof Error?e.message:'Gagal membatalkan publish')}finally{setBusy(false)}}
 if(loading&&!data)return <AppShell title="Gradebook"><Card className="h-56 animate-pulse"/></AppShell>
 if(!data)return <AppShell title="Gradebook"><Card className="p-6 text-red-600">{error||'Gradebook tidak ditemukan.'}</Card></AppShell>
 return <AppShell title={data.classroom.subject?.name||'Gradebook'}>
  <div className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge tone={data.settings.status==='published'?'green':'slate'}>{data.settings.status==='published'?'Nilai dipublikasikan':'Draft nilai'}</Badge><span className="text-xs text-slate-400">{data.classroom.class_group?.name} • {data.classroom.semester?.name}</span></div><h2 className="mt-3 text-2xl font-semibold tracking-tight">{data.classroom.subject?.name}</h2><p className="mt-1 text-sm text-slate-500">{data.summary.students} siswa • rata-rata kelas {fmt(data.summary.class_average)} • {data.summary.at_risk} perlu perhatian</p></div><div className="flex gap-2"><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Refresh</Button>{data.settings.status==='published'?<Button variant="secondary" onClick={unpublish} disabled={busy}><XCircle size={16}/>Tarik publikasi</Button>:<Button onClick={publish} disabled={busy}><Send size={16}/>Publikasikan nilai</Button>}</div></div>
  {error&&<Card className="mb-5 border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</Card>}
  <div className="grid gap-4 lg:grid-cols-[320px_1fr]"><Card className="h-fit p-5"><div className="flex items-center gap-2"><SlidersHorizontal size={17} className="text-blue-600"/><h3 className="font-semibold">Pengaturan bobot</h3></div><p className="mt-1 text-xs leading-5 text-slate-500">Perubahan pengaturan mengembalikan status nilai menjadi draft.</p><label className="mt-5 block text-xs font-medium text-slate-600">Bobot tugas (%)</label><Input className="mt-1" type="number" min={0} max={100} value={aw} onChange={e=>setAw(Number(e.target.value))}/><label className="mt-4 block text-xs font-medium text-slate-600">Bobot quiz (%)</label><Input className="mt-1" type="number" min={0} max={100} value={qw} onChange={e=>setQw(Number(e.target.value))}/><div className={`mt-2 text-xs ${aw+qw===100?'text-emerald-600':'text-red-600'}`}>Total bobot: {aw+qw}%</div><label className="mt-4 block text-xs font-medium text-slate-600">KKM / nilai lulus</label><Input className="mt-1" type="number" min={0} max={100} value={passing} onChange={e=>setPassing(Number(e.target.value))}/><label className="mt-4 flex cursor-pointer items-start gap-2 rounded-xl bg-slate-50 p-3"><input type="checkbox" className="mt-0.5" checked={missing} onChange={e=>setMissing(e.target.checked)}/><span><span className="block text-xs font-medium">Nilai kosong = 0 setelah deadline</span><span className="mt-1 block text-[11px] leading-4 text-slate-500">Jika nonaktif, komponen yang belum dinilai tidak ikut rata-rata sementara.</span></span></label><Button className="mt-4 w-full" onClick={save} disabled={busy||aw+qw!==100}><Save size={16}/>Simpan pengaturan</Button></Card>
   <div className="space-y-4"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label="Rata-rata kelas" value={fmt(data.summary.class_average)}/><Metric label="Tingkat lulus" value={data.summary.pass_rate==null?'—':`${fmt(data.summary.pass_rate)}%`}/><Metric label="Perlu perhatian" value={String(data.summary.at_risk)}/><Metric label="Materi publish" value={String(data.summary.published_materials)}/></div>
   <Card className="overflow-hidden p-0"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-semibold">Nilai siswa</h3><p className="mt-1 text-xs text-slate-500">Nilai akhir dihitung dari komponen yang sudah tersedia, bobot, dan adjustment.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Siswa</th><th className="px-4 py-3">Tugas</th><th className="px-4 py-3">Quiz</th><th className="px-4 py-3">Progress</th><th className="px-4 py-3">Adj.</th><th className="px-4 py-3">Nilai akhir</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Risiko</th></tr></thead><tbody>{data.students.map(row=><StudentRow key={row.student.id} row={row} classroomId={id} onSaved={load}/>)}</tbody></table></div></Card></div>
  </div>
 </AppShell>
}
function Metric({label,value}:{label:string;value:string}){return <Card className="p-4"><p className="text-[11px] text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></Card>}
function StudentRow({row,classroomId,onSaved}:{row:GradeStudent;classroomId:number;onSaved:()=>void}){
 const [editing,setEditing]=useState(false);const [points,setPoints]=useState(row.adjustment);const [note,setNote]=useState(row.adjustment_note||'');const [busy,setBusy]=useState(false)
 const save=async()=>{setBusy(true);try{await gradeApi.teacher.adjustment(classroomId,row.student.id,{points,note});setEditing(false);onSaved()}finally{setBusy(false)}}
 return <tr className="border-t border-slate-100 align-top"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100"><UserRound size={16}/></div><div><p className="font-medium text-slate-900">{row.student.name}</p><p className="text-xs text-slate-400">{row.student.username}</p></div></div></td><td className="px-4 py-4 font-medium">{fmt(row.assignment_average)}</td><td className="px-4 py-4 font-medium">{fmt(row.quiz_average)}</td><td className="px-4 py-4"><div className="w-28"><div className="mb-1 flex justify-between text-[10px] text-slate-400"><span>Materi</span><span>{fmt(row.material_progress)}%</span></div><Progress value={row.material_progress}/></div></td><td className="px-4 py-4">{editing?<div className="w-48 space-y-2"><Input type="number" min={-20} max={20} value={points} onChange={e=>setPoints(Number(e.target.value))}/><Input placeholder="Catatan adjustment" value={note} onChange={e=>setNote(e.target.value)}/><div className="flex gap-1"><Button size="sm" onClick={save} disabled={busy}>Simpan</Button><Button size="sm" variant="ghost" onClick={()=>setEditing(false)}>Batal</Button></div></div>:<button onClick={()=>setEditing(true)} className="rounded-lg px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50">{row.adjustment>0?'+':''}{row.adjustment.toFixed(1)}</button>}</td><td className="px-4 py-4"><div className="flex items-center gap-2"><span className="text-lg font-semibold">{fmt(row.final_score)}</span>{row.letter_grade&&<Badge>{row.letter_grade}</Badge>}</div></td><td className="px-4 py-4">{row.final_score==null?<Badge tone="slate">Belum lengkap</Badge>:row.passed?<Badge tone="green"><CheckCircle2 size={12}/>Lulus</Badge>:<Badge tone="red">Belum lulus</Badge>}</td><td className="px-4 py-4">{row.risk_flags.length?<div className="space-y-1">{row.risk_flags.map(x=><span key={x} className="flex items-center gap-1 text-[11px] text-amber-700"><AlertTriangle size={12}/>{x.replaceAll('_',' ')}</span>)}</div>:<span className="text-xs text-emerald-600">Aman</span>}</td></tr>
}
