import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Clock3, Crosshair, MapPin, Play, QrCode, RefreshCw, Square, UserCheck, Users } from 'lucide-react'
import AppShell from '@/components/layout/AppShell'
import { Button, Card } from '@/components/ui'
import { apiRequest, ApiError } from '@/lib/api/client'
import { DynamicQRCode } from '@/components/shared/DynamicQRCode'

type Classroom={id:number;title:string;teaching_assignment?:{subject?:{name:string};class_group?:{name:string}}}
type Session={id:number;title:string;status:string;opens_at:string;late_after?:string|null;closes_at:string;allow_manual:boolean;require_gps:boolean;latitude?:number|null;longitude?:number|null;radius_meters:number;require_dynamic_qr:boolean;qr_rotation_seconds:number;require_selfie:boolean;records_count?:number;classroom?:Classroom}
type Student={id:number;name:string;username:string}
type AttendanceRow={id:number;student_id:number;status:string;method:string;checked_in_at?:string|null;distance_meters?:number|null;selfie_path?:string|null;student?:Student}
type Detail={session:Session;roster:{student:Student;record?:AttendanceRow|null}[];summary:Record<string,number>}
type Data<T>={data:T}

function toIso(v:string){return v?new Date(v).toISOString():undefined}
function localValue(date:Date){const p=(n:number)=>String(n).padStart(2,'0');return `${date.getFullYear()}-${p(date.getMonth()+1)}-${p(date.getDate())}T${p(date.getHours())}:${p(date.getMinutes())}`}

export default function TeacherAttendance(){
 const [classes,setClasses]=useState<Classroom[]>([]),[sessions,setSessions]=useState<Session[]>([]),[selectedId,setSelectedId]=useState<number|undefined>(),[detail,setDetail]=useState<Detail|null>(null),[qr,setQr]=useState<{token:string;expires_at:string;rotation_seconds:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const now=new Date(), close=new Date(Date.now()+60*60*1000), late=new Date(Date.now()+15*60*1000)
 const [form,setForm]=useState({classroom_id:'',title:'Absensi Pertemuan',opens_at:localValue(now),late_after:localValue(late),closes_at:localValue(close),allow_manual:true,require_gps:false,latitude:'',longitude:'',radius_meters:'100',require_dynamic_qr:true,qr_rotation_seconds:'30',require_selfie:false})
 const selected=useMemo(()=>sessions.find(s=>s.id===selectedId),[sessions,selectedId])
 async function load(){const [c,s]=await Promise.all([apiRequest<Data<Classroom[]>>('/teacher/attendance/classrooms'),apiRequest<Data<Session[]>>('/teacher/attendance/sessions')]);setClasses(c.data);setSessions(s.data);if(!form.classroom_id&&c.data[0])setForm(v=>({...v,classroom_id:String(c.data[0].id)}));if(!selectedId&&s.data[0])setSelectedId(s.data[0].id)}
 async function loadDetail(id:number){const r=await apiRequest<Data<Detail>>(`/teacher/attendance/sessions/${id}`);setDetail(r.data)}
 async function loadQr(id:number){try{const r=await apiRequest<Data<{token:string;expires_at:string;rotation_seconds:number}>>(`/teacher/attendance/sessions/${id}/qr`);setQr(r.data)}catch{setQr(null)}}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 useEffect(()=>{if(selectedId){loadDetail(selectedId).catch(e=>setError(e.message)); if(selected?.require_dynamic_qr)loadQr(selectedId)}},[selectedId,selected?.require_dynamic_qr])
 useEffect(()=>{if(!selectedId||!selected?.require_dynamic_qr||selected.status!=='open')return; const t=setInterval(()=>loadQr(selectedId),5000);return()=>clearInterval(t)},[selectedId,selected?.require_dynamic_qr,selected?.status])
 async function create(){setBusy(true);setError('');try{const body={...form,classroom_id:Number(form.classroom_id),opens_at:toIso(form.opens_at),late_after:form.late_after?toIso(form.late_after):null,closes_at:toIso(form.closes_at),latitude:form.latitude?Number(form.latitude):null,longitude:form.longitude?Number(form.longitude):null,radius_meters:Number(form.radius_meters),qr_rotation_seconds:Number(form.qr_rotation_seconds)};const r=await apiRequest<Data<Session>>('/teacher/attendance/sessions',{method:'POST',body:JSON.stringify(body)});await load();setSelectedId(r.data.id)}catch(e){setError(e instanceof ApiError?e.message:'Gagal membuat sesi')}finally{setBusy(false)}}
 function useLocation(){navigator.geolocation.getCurrentPosition(p=>setForm(v=>({...v,latitude:String(p.coords.latitude),longitude:String(p.coords.longitude)})),()=>setError('Browser tidak dapat mengambil lokasi. Pastikan izin lokasi diberikan.'),{enableHighAccuracy:true})}
 async function action(kind:'start'|'close'){if(!selectedId)return;await apiRequest(`/teacher/attendance/sessions/${selectedId}/${kind}`,{method:'POST',body:JSON.stringify({})});await load();await loadDetail(selectedId);if(kind==='start')await loadQr(selectedId)}
 async function manual(studentId:number,status:string){if(!selectedId)return;await apiRequest(`/teacher/attendance/sessions/${selectedId}/records`,{method:'PUT',body:JSON.stringify({student_id:studentId,status})});await loadDetail(selectedId)}
 return <AppShell title="Absensi">
  <div className="grid gap-6 2xl:grid-cols-[380px_1fr]">
   <div className="space-y-5">
    <Card className="p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-600">Attendance session</p><h2 className="mt-1 text-xl font-semibold">Buka sesi baru</h2>
      <select value={form.classroom_id} onChange={e=>setForm({...form,classroom_id:e.target.value})} className="mt-4 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm">{classes.map(c=><option key={c.id} value={c.id}>{c.title} — {c.teaching_assignment?.class_group?.name}</option>)}</select>
      <input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-3 w-full rounded-xl border border-slate-200 px-3 py-3 text-sm" placeholder="Judul sesi"/>
      <div className="mt-3 grid gap-3 sm:grid-cols-3 2xl:grid-cols-1"><label className="text-xs text-slate-500">Buka<input type="datetime-local" value={form.opens_at} onChange={e=>setForm({...form,opens_at:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs text-slate-500">Terlambat setelah<input type="datetime-local" value={form.late_after} onChange={e=>setForm({...form,late_after:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs text-slate-500">Tutup<input type="datetime-local" value={form.closes_at} onChange={e=>setForm({...form,closes_at:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm"/></label></div>
      <div className="mt-4 space-y-2">{[['require_dynamic_qr','Dynamic QR / code'],['require_gps','GPS radius'],['require_selfie','Selfie evidence'],['allow_manual','Manual guru']].map(([k,l])=><label key={k} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-2.5 text-sm"><span>{l}</span><input type="checkbox" checked={Boolean((form as any)[k])} onChange={e=>setForm(v=>({...v,[k]:e.target.checked}))}/></label>)}</div>
      {form.require_gps&&<div className="mt-3 rounded-xl border border-blue-100 bg-blue-50/50 p-3"><div className="flex items-center justify-between"><b className="text-xs text-blue-900">Geofence</b><button onClick={useLocation} className="text-xs font-semibold text-blue-700"><Crosshair size={13} className="inline"/> Gunakan lokasi saya</button></div><div className="mt-2 grid grid-cols-2 gap-2"><input value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} placeholder="Latitude" className="rounded-lg border border-blue-100 px-2 py-2 text-xs"/><input value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} placeholder="Longitude" className="rounded-lg border border-blue-100 px-2 py-2 text-xs"/></div><input value={form.radius_meters} onChange={e=>setForm({...form,radius_meters:e.target.value})} className="mt-2 w-full rounded-lg border border-blue-100 px-2 py-2 text-xs" placeholder="Radius meter"/></div>}
      <Button className="mt-4 w-full" disabled={busy} onClick={create}>{busy?'Menyimpan...':'Buat Sesi Absensi'}</Button>
    </Card>
    <Card className="p-3"><div className="flex items-center justify-between px-2 py-2"><b className="text-sm">Sesi terbaru</b><Button size="sm" variant="ghost" onClick={()=>load()}><RefreshCw size={14}/></Button></div>{sessions.map(s=><button key={s.id} onClick={()=>setSelectedId(s.id)} className={`mb-1 w-full rounded-xl px-3 py-3 text-left ${selectedId===s.id?'bg-blue-50':'hover:bg-slate-50'}`}><div className="flex items-center justify-between gap-2"><b className="text-sm">{s.title}</b><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold ${s.status==='open'?'bg-emerald-50 text-emerald-700':s.status==='closed'?'bg-slate-100 text-slate-500':'bg-amber-50 text-amber-700'}`}>{s.status.toUpperCase()}</span></div><p className="mt-1 text-xs text-slate-500">{s.classroom?.title}</p></button>)}</Card>
   </div>
   <div className="space-y-5">
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {!selected?<Card className="p-10 text-center text-sm text-slate-500">Pilih sesi untuk melihat detail.</Card>:<>
     <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-slate-400">{selected.classroom?.teaching_assignment?.class_group?.name}</p><h2 className="mt-1 text-2xl font-semibold tracking-tight">{selected.title}</h2><div className="mt-3 flex flex-wrap gap-2 text-xs text-slate-500"><span className="rounded-lg bg-slate-100 px-2 py-1"><Clock3 size={13} className="mr-1 inline"/>{new Date(selected.opens_at).toLocaleString('id-ID')}</span>{selected.require_gps&&<span className="rounded-lg bg-slate-100 px-2 py-1"><MapPin size={13} className="mr-1 inline"/>Radius {selected.radius_meters}m</span>}{selected.require_dynamic_qr&&<span className="rounded-lg bg-slate-100 px-2 py-1"><QrCode size={13} className="mr-1 inline"/>Dynamic {selected.qr_rotation_seconds}s</span>}</div></div><div className="flex gap-2">{selected.status!=='open'&&selected.status!=='closed'&&<Button onClick={()=>action('start')}><Play size={15}/> Mulai</Button>}{selected.status==='open'&&<Button variant="secondary" onClick={()=>action('close')}><Square size={15}/> Tutup</Button>}</div></div></Card>
     {selected.require_dynamic_qr&&selected.status==='open'&&<Card className="overflow-hidden p-0"><div className="grid gap-0 md:grid-cols-[1fr_280px]"><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-blue-600">Dynamic QR</p><div className="mt-3 font-mono text-4xl font-black tracking-[.18em] text-slate-950">{qr?.token??'Loading...'}</div><p className="mt-3 max-w-xl text-sm leading-6 text-slate-500">QR dan kode berganti otomatis setiap {qr?.rotation_seconds??selected.qr_rotation_seconds} detik. Siswa dapat memindai QR menggunakan kamera EduNova atau memasukkan kode secara manual.</p></div><div className="grid min-h-72 place-items-center bg-slate-950 p-6 text-center text-white"><div><DynamicQRCode value={qr?.token}/><p className="mt-3 text-xs text-slate-300">Token aktif</p><p className="mt-1 text-sm font-semibold">{qr?.expires_at?`berakhir ${new Date(qr.expires_at).toLocaleTimeString('id-ID')}`:'...'}</p></div></div></div></Card>}
     <div className="grid gap-4 sm:grid-cols-3"><Card className="p-4"><Users size={18} className="text-blue-600"/><div className="mt-3 text-2xl font-semibold">{detail?.roster.length??0}</div><p className="text-xs text-slate-500">Siswa</p></Card><Card className="p-4"><UserCheck size={18} className="text-emerald-600"/><div className="mt-3 text-2xl font-semibold">{(detail?.summary.present??0)+(detail?.summary.late??0)}</div><p className="text-xs text-slate-500">Tercatat hadir</p></Card><Card className="p-4"><CheckCircle2 size={18} className="text-amber-600"/><div className="mt-3 text-2xl font-semibold">{detail?.summary.late??0}</div><p className="text-xs text-slate-500">Terlambat</p></Card></div>
     <Card className="overflow-hidden p-0"><div className="border-b border-slate-100 px-5 py-4"><b>Daftar siswa</b></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-400"><tr><th className="px-5 py-3">Siswa</th><th>Status</th><th>Metode</th><th>Waktu</th><th className="px-5">Manual</th></tr></thead><tbody>{detail?.roster.map(r=><tr key={r.student.id} className="border-t border-slate-100"><td className="px-5 py-4"><b>{r.student.name}</b><div className="text-xs text-slate-400">{r.student.username}</div></td><td><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{r.record?.status??'belum'}</span></td><td className="text-xs text-slate-500">{r.record?.method??'-'}</td><td className="text-xs text-slate-500">{r.record?.checked_in_at?new Date(r.record.checked_in_at).toLocaleTimeString('id-ID'):'-'}</td><td className="px-5"><select disabled={!selected.allow_manual} value={r.record?.status??''} onChange={e=>e.target.value&&manual(r.student.id,e.target.value)} className="rounded-lg border border-slate-200 bg-white px-2 py-2 text-xs"><option value="">Ubah...</option><option value="present">Hadir</option><option value="late">Terlambat</option><option value="sick">Sakit</option><option value="permission">Izin</option><option value="dispensation">Dispensasi</option><option value="absent">Alpa</option></select></td></tr>)}</tbody></table></div></Card>
    </>}
   </div>
  </div>
 </AppShell>
}
