import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CalendarClock, Check, ClipboardCheck, FilePlus2, Plus, Save, Send, Trash2, UsersRound } from 'lucide-react'
import { Link, useParams } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { Badge, Button, Card } from '@/components/ui'
import { assignmentApi, type Assignment, type AssignmentSubmission, type RubricCriterion } from '@/features/assignment/api'

export default function TeacherAssignmentEditor(){
 const{id}=useParams();const assignmentId=Number(id)
 const[item,setItem]=useState<Assignment|null>(null),[subs,setSubs]=useState<AssignmentSubmission[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const[form,setForm]=useState({title:'',instructions:'',due_at:'',max_score:100,allow_text:true,allow_link:true,allow_file:true,allow_resubmit:true,max_file_mb:20})
 const[rubric,setRubric]=useState<Array<{title:string;description:string;max_points:number}>>([])
 async function load(){setLoading(true);setError('');try{const[a,b]=await Promise.all([assignmentApi.teacher.get(assignmentId),assignmentApi.teacher.submissions(assignmentId)]);setItem(a.data);setSubs(b.data);setForm({title:a.data.title,instructions:a.data.instructions??'',due_at:toLocal(a.data.due_at),max_score:Number(a.data.max_score),allow_text:a.data.allow_text,allow_link:a.data.allow_link,allow_file:a.data.allow_file,allow_resubmit:a.data.allow_resubmit,max_file_mb:a.data.max_file_mb});setRubric((a.data.rubric_criteria??a.data.rubricCriteria??[]).map(r=>({title:r.title,description:r.description??'',max_points:Number(r.max_points)})))}catch(e){setError(e instanceof Error?e.message:'Gagal memuat tugas.')}finally{setLoading(false)}}
 useEffect(()=>{if(assignmentId)void load()},[assignmentId])
 async function save(){setSaving(true);setError('');try{await assignmentApi.teacher.update(assignmentId,{...form,due_at:form.due_at?new Date(form.due_at).toISOString():null});await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan tugas.')}finally{setSaving(false)}}
 async function publish(){if(!item)return;setSaving(true);try{await assignmentApi.teacher.publish(item.id,item.status!=='published');await load()}catch(e){setError(e instanceof Error?e.message:'Gagal mengubah status publish.')}finally{setSaving(false)}}
 async function saveRubric(){setSaving(true);try{await assignmentApi.teacher.saveRubric(assignmentId,rubric);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan rubrik.')}finally{setSaving(false)}}
 async function upload(file?:File){if(!file)return;setSaving(true);try{await assignmentApi.teacher.addAttachment(assignmentId,file);await load()}catch(e){setError(e instanceof Error?e.message:'Upload lampiran gagal.')}finally{setSaving(false)}}
 async function removeAttachment(id:number){if(!confirm('Hapus lampiran ini?'))return;await assignmentApi.teacher.removeAttachment(id);await load()}
 const pending=useMemo(()=>subs.filter(s=>['submitted','late'].includes(s.status)).length,[subs])
 if(loading)return <AppShell title="Penugasan"><Card className="h-72 animate-pulse bg-slate-100"/></AppShell>
 if(!item)return <AppShell title="Penugasan"><Card className="p-6">Tugas tidak ditemukan.</Card></AppShell>
 return <AppShell title="Kelola Tugas">
 <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to="/assignments" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/>Assignment Center</Link><div className="flex gap-2"><Button variant="secondary" onClick={save} disabled={saving}><Save size={15}/>Simpan</Button><Button onClick={publish} disabled={saving}>{item.status==='published'?<><Check size={15}/>Published</>:<><Send size={15}/>Publish</>}</Button></div></div>
 {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 <Card className="overflow-hidden p-0"><div className="bg-[#0D1B36] p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">{item.classroom?.teaching_assignment?.subject?.name} • {item.classroom?.teaching_assignment?.class_group?.name}</p><h2 className="mt-2 text-2xl font-semibold">{item.title}</h2><p className="mt-2 text-sm text-slate-300">Deadline {item.due_at?formatDate(item.due_at):'tidak ditentukan'}</p></div><Badge tone={item.status==='published'?'green':'amber'}>{item.status}</Badge></div></div></Card>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_.7fr]"><div className="space-y-6">
  <Card className="p-5"><h3 className="text-sm font-semibold">Pengaturan tugas</h3><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Judul"><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))}/></Field><Field label="Deadline"><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" type="datetime-local" value={form.due_at} onChange={e=>setForm(v=>({...v,due_at:e.target.value}))}/></Field><Field label="Nilai maksimum"><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" type="number" min="1" value={form.max_score} onChange={e=>setForm(v=>({...v,max_score:Number(e.target.value)}))}/></Field><Field label="Maks file (MB)"><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" type="number" min="1" max="64" value={form.max_file_mb} onChange={e=>setForm(v=>({...v,max_file_mb:Number(e.target.value)}))}/></Field></div><Field label="Instruksi"><textarea className="mt-1 min-h-36 w-full rounded-xl border border-slate-200 p-3 text-sm" value={form.instructions} onChange={e=>setForm(v=>({...v,instructions:e.target.value}))}/></Field><div className="mt-4 grid gap-2 sm:grid-cols-2"><CheckBox label="Jawaban teks" checked={form.allow_text} onChange={v=>setForm(x=>({...x,allow_text:v}))}/><CheckBox label="Link" checked={form.allow_link} onChange={v=>setForm(x=>({...x,allow_link:v}))}/><CheckBox label="Upload file" checked={form.allow_file} onChange={v=>setForm(x=>({...x,allow_file:v}))}/><CheckBox label="Resubmit sebelum deadline" checked={form.allow_resubmit} onChange={v=>setForm(x=>({...x,allow_resubmit:v}))}/></div></Card>
  <Card className="p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold">Rubrik penilaian</h3><p className="mt-1 text-xs text-slate-500">Total poin rubrik otomatis menjadi nilai maksimum.</p></div><Button variant="secondary" size="sm" onClick={()=>setRubric(v=>[...v,{title:'',description:'',max_points:10}])}><Plus size={14}/>Kriteria</Button></div><div className="mt-4 space-y-3">{rubric.map((r,i)=><div key={i} className="grid gap-3 rounded-xl border border-slate-200 p-3 sm:grid-cols-[1fr_1.4fr_110px_36px]"><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" placeholder="Kriteria" value={r.title} onChange={e=>setRubric(v=>v.map((x,j)=>j===i?{...x,title:e.target.value}:x))}/><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" placeholder="Deskripsi" value={r.description} onChange={e=>setRubric(v=>v.map((x,j)=>j===i?{...x,description:e.target.value}:x))}/><input className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm" type="number" min="1" value={r.max_points} onChange={e=>setRubric(v=>v.map((x,j)=>j===i?{...x,max_points:Number(e.target.value)}:x))}/><button onClick={()=>setRubric(v=>v.filter((_,j)=>j!==i))} className="grid h-10 w-10 place-items-center rounded-xl text-red-500 hover:bg-red-50"><Trash2 size={15}/></button></div>)}{!rubric.length&&<p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">Belum menggunakan rubrik. Nilai dapat diberikan secara langsung.</p>}</div><div className="mt-4 flex justify-end"><Button variant="secondary" onClick={saveRubric}><ClipboardCheck size={15}/>Simpan rubrik ({rubric.reduce((n,r)=>n+Number(r.max_points||0),0)} poin)</Button></div></Card>
 </div><div className="space-y-6">
  <Card className="p-5"><h3 className="text-sm font-semibold">Ringkasan submission</h3><div className="mt-4 grid grid-cols-2 gap-3"><Mini icon={<UsersRound size={16}/>} n={subs.length} label="Masuk"/><Mini icon={<ClipboardCheck size={16}/>} n={pending} label="Perlu review"/></div></Card>
  <Card className="p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Lampiran tugas</h3><label className="cursor-pointer"><input type="file" className="hidden" onChange={e=>void upload(e.target.files?.[0])}/><span className="inline-flex items-center gap-1 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold"><FilePlus2 size={14}/>Upload</span></label></div><div className="mt-3 space-y-2">{(item.attachments??[]).map(f=><div key={f.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><a href={f.file_url??'#'} target="_blank" rel="noreferrer" className="min-w-0 truncate text-xs font-semibold text-blue-700">{f.original_name}</a><button onClick={()=>void removeAttachment(f.id)} className="text-red-500"><Trash2 size={14}/></button></div>)}{!(item.attachments??[]).length&&<p className="text-xs text-slate-400">Tidak ada lampiran.</p>}</div></Card>
  <Card className="p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Review queue</h3><Badge tone={pending?'amber':'green'}>{pending} menunggu</Badge></div><div className="mt-4 space-y-2">{subs.map(s=><Link key={s.id} to={`/teacher/submissions/${s.id}`} className="flex items-center justify-between rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><div className="min-w-0"><p className="truncate text-xs font-semibold">{s.student?.name}</p><p className="mt-1 text-[10px] text-slate-400">Percobaan {s.attempt_no} • {s.submitted_at?formatDate(s.submitted_at):'Draft'}</p></div><Badge tone={tone(s.status)}>{s.status}</Badge></Link>)}{!subs.length&&<p className="text-xs text-slate-400">Belum ada submission.</p>}</div></Card>
 </div></div>
 </AppShell>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">{label}</span>{children}</label>}
function CheckBox({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2.5 text-xs font-medium"><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Mini({icon,n,label}:{icon:React.ReactNode;n:number;label:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="text-slate-400">{icon}</div><b className="mt-2 block text-xl">{n}</b><p className="text-[10px] text-slate-500">{label}</p></div>}
function formatDate(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
function toLocal(v?:string|null){if(!v)return'';const d=new Date(v);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
function tone(s:string):'blue'|'green'|'amber'|'red'|'slate'{return s==='late'?'red':s==='submitted'?'amber':s==='returned'?'green':s==='graded'?'blue':'slate'}
