import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, ExternalLink, FileText, Send } from 'lucide-react'
import { Link, useParams } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { Badge, Button, Card } from '@/components/ui'
import { assignmentApi, type AssignmentSubmission } from '@/features/assignment/api'

export default function TeacherSubmissionReview(){
 const{id}=useParams();const sid=Number(id);const[item,setItem]=useState<AssignmentSubmission|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[feedback,setFeedback]=useState(''),[score,setScore]=useState(0),[rubricScores,setRubricScores]=useState<Record<number,number>>({})
 async function load(){setLoading(true);try{const r=await assignmentApi.teacher.submission(sid);setItem(r.data);setFeedback(r.data.feedback??'');setScore(Number(r.data.score??0));const map:Record<number,number>={};for(const rs of (r.data.rubric_scores??r.data.rubricScores??[]))map[rs.rubric_criterion_id]=Number(rs.points);setRubricScores(map)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat submission.')}finally{setLoading(false)}}
 useEffect(()=>{if(sid)void load()},[sid])
 const criteria=item?.assignment?.rubric_criteria??item?.assignment?.rubricCriteria??[]
 const rubricTotal=useMemo(()=>criteria.reduce((n,c)=>n+Number(rubricScores[c.id]??0),0),[criteria,rubricScores])
 async function grade(){if(!item)return;setSaving(true);try{await assignmentApi.teacher.grade(item.id,{score:criteria.length?undefined:score,feedback,rubric_scores:criteria.map(c=>({criterion_id:c.id,points:Number(rubricScores[c.id]??0)}))});await load()}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan nilai.')}finally{setSaving(false)}}
 async function returnStudent(){if(!item)return;setSaving(true);try{await assignmentApi.teacher.returnToStudent(item.id);await load()}catch(e){setError(e instanceof Error?e.message:'Gagal mengembalikan tugas.')}finally{setSaving(false)}}
 if(loading)return <AppShell title="Review Submission"><Card className="h-72 animate-pulse bg-slate-100"/></AppShell>
 if(!item)return <AppShell title="Review Submission"><Card className="p-6">Submission tidak ditemukan.</Card></AppShell>
 const a=item.assignment!
 return <AppShell title="Review Submission"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to={`/teacher/assignments/${a.id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft size={16}/>Kembali ke tugas</Link><Badge tone={tone(item.status)}>{item.status}</Badge></div>{error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="space-y-6"><Card className="p-6"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-blue-600">{a.title}</p><h2 className="mt-2 text-xl font-semibold">{item.student?.name}</h2><p className="mt-1 text-xs text-slate-500">{item.student?.username} • Percobaan {item.attempt_no} • {item.submitted_at?formatDate(item.submitted_at):'Belum submit'}</p>{item.is_late&&<Badge tone="red" className="mt-3">Late submission</Badge>}</Card>
 <Card className="p-6"><h3 className="text-sm font-semibold">Jawaban siswa</h3>{item.text_answer?<p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-700">{item.text_answer}</p>:<p className="mt-4 text-sm text-slate-400">Tidak ada jawaban teks.</p>}{item.link_url&&<a href={item.link_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-blue-700"><ExternalLink size={15}/>Buka link submission</a>}<div className="mt-5 space-y-2">{(item.files??[]).map(f=><a key={f.id} href={f.file_url??'#'} target="_blank" rel="noreferrer" className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-medium hover:bg-slate-50"><FileText size={16} className="text-blue-600"/><span className="truncate">{f.original_name}</span></a>)}</div></Card></div>
 <div className="space-y-6"><Card className="p-6"><h3 className="text-sm font-semibold">Penilaian</h3>{criteria.length?<div className="mt-4 space-y-3">{criteria.map(c=><div key={c.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold">{c.title}</p><p className="mt-1 text-[11px] leading-5 text-slate-500">{c.description}</p></div><div className="flex items-center gap-1"><input type="number" min="0" max={Number(c.max_points)} value={rubricScores[c.id]??0} onChange={e=>setRubricScores(v=>({...v,[c.id]:Number(e.target.value)}))} className="h-9 w-20 rounded-lg border border-slate-200 px-2 text-right text-sm"/><span className="text-xs text-slate-400">/{Number(c.max_points)}</span></div></div></div>)}<div className="flex items-center justify-between rounded-xl bg-slate-950 p-4 text-white"><span className="text-xs">Total nilai</span><b className="text-xl">{rubricTotal}/{Number(a.max_score)}</b></div></div>:<label className="mt-4 block"><span className="text-xs font-semibold text-slate-500">Nilai / {Number(a.max_score)}</span><input type="number" min="0" max={Number(a.max_score)} value={score} onChange={e=>setScore(Number(e.target.value))} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></label>}<label className="mt-4 block"><span className="text-xs font-semibold text-slate-500">Feedback guru</span><textarea value={feedback} onChange={e=>setFeedback(e.target.value)} className="mt-2 min-h-32 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Berikan feedback yang spesifik dan actionable..."/></label><Button className="mt-4 w-full" onClick={grade} disabled={saving}><CheckCircle2 size={15}/>Simpan penilaian</Button>{item.status==='graded'&&<Button variant="dark" className="mt-2 w-full" onClick={returnStudent} disabled={saving}><Send size={15}/>Kembalikan ke siswa</Button>}{item.status==='returned'&&<div className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-700">Nilai dan feedback sudah dikembalikan ke siswa.</div>}</Card></div></div>
 </AppShell>
}
function formatDate(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
function tone(s:string):'blue'|'green'|'amber'|'red'|'slate'{return s==='late'?'red':s==='submitted'?'amber':s==='returned'?'green':s==='graded'?'blue':'slate'}
