import { useEffect, useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, Clock3, Layers3, Plus, UsersRound } from 'lucide-react'
import { Link } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Badge, Button, Card } from '@/components/ui'
import { classroomApi, type AssignmentMeta, type Classroom } from '@/features/classroom/api'

export default function TeacherClassrooms(){
 const [items,setItems]=useState<Classroom[]>([]),[meta,setMeta]=useState<AssignmentMeta[]>([]),[loading,setLoading]=useState(true),[showCreate,setShowCreate]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const [form,setForm]=useState({teaching_assignment_id:0,title:'',description:''})
 async function load(){setLoading(true);setError('');try{const [a,b]=await Promise.all([classroomApi.teacher.list(),classroomApi.teacher.meta()]);setItems(a.data);setMeta(b.data)}catch(e){setError(e instanceof Error?e.message:'Gagal memuat kelas digital.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const available=useMemo(()=>meta.filter(x=>!x.classroom),[meta])
 async function create(){if(!form.teaching_assignment_id||!form.title.trim())return;setSaving(true);setError('');try{await classroomApi.teacher.create(form);setShowCreate(false);setForm({teaching_assignment_id:0,title:'',description:''});await load()}catch(e){setError(e instanceof Error?e.message:'Gagal membuat kelas.')}finally{setSaving(false)}}
 return <AppShell title="Kelas Digital"><PageHeader eyebrow="Digital Classroom • Phase 05" title="Kelola ruang belajar" description="Bangun struktur materi, publish konten, dan siapkan pengalaman belajar siswa dari satu workspace." action={<Button onClick={()=>setShowCreate(v=>!v)}><Plus size={16}/>{showCreate?'Tutup':'Buat kelas digital'}</Button>}/>
 {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 {showCreate&&<Card className="mb-6 p-5"><div className="grid gap-4 lg:grid-cols-[1fr_1fr_1.4fr_auto] lg:items-end"><Field label="Penugasan"><select value={form.teaching_assignment_id} onChange={e=>{const id=Number(e.target.value);const a=meta.find(x=>x.id===id);setForm(v=>({...v,teaching_assignment_id:id,title:a?.subject?.name??v.title}))}} className="focus-ring h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value={0}>Pilih penugasan</option>{available.map(a=><option key={a.id} value={a.id}>{a.subject?.name} • {a.class_group?.name}</option>)}</select></Field><Field label="Nama kelas"><input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} className="focus-ring h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Contoh: Fotografi Digital"/></Field><Field label="Deskripsi"><input value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} className="focus-ring h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Ringkasan kelas..."/></Field><Button disabled={saving||!available.length} onClick={create}>{saving?'Menyimpan...':'Buat kelas'}</Button></div>{!available.length&&<p className="mt-3 text-xs text-amber-700">Semua penugasan mengajar sudah memiliki kelas digital.</p>}</Card>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<BookOpen/>} value={String(items.length)} label="Kelas digital"/><Stat icon={<CheckCircle2/>} value={String(items.filter(x=>x.status==='published').length)} label="Sudah publish"/><Stat icon={<Layers3/>} value={String(items.reduce((n,x)=>n+(x.materials_count??0),0))} label="Total materi"/><Stat icon={<UsersRound/>} value={String(meta.length)} label="Penugasan aktif"/></div>
 <div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3].map(i=><Card key={i} className="h-56 animate-pulse bg-slate-100"/>):items.map(c=><Card key={c.id} className="overflow-hidden p-0"><div className="bg-[#0D1B36] p-5 text-white dashboard-grid"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-blue-300">{c.code||c.teaching_assignment?.subject?.code}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{c.title}</h3><p className="mt-1 text-xs text-slate-300">{c.teaching_assignment?.class_group?.name} • {c.teaching_assignment?.semester?.name}</p></div><Badge tone={c.status==='published'?'green':'amber'}>{c.status==='published'?'Published':'Draft'}</Badge></div></div><div className="p-5"><p className="min-h-10 text-xs leading-5 text-slate-500">{c.description||'Belum ada deskripsi kelas.'}</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini icon={<Layers3 size={15}/>} n={c.sections_count??0} label="Chapter"/><Mini icon={<Clock3 size={15}/>} n={c.materials_count??0} label="Materi"/></div><Link to={`/teacher/classrooms/${c.id}`}><Button className="mt-5 w-full" variant="dark">Kelola kelas</Button></Link></div></Card>)}</div>
 {!loading&&!items.length&&<Card className="mt-6 border-dashed p-8 text-center shadow-none"><BookOpen className="mx-auto text-slate-300" size={30}/><p className="mt-3 text-sm font-semibold">Belum ada kelas digital</p><p className="mt-1 text-xs text-slate-500">Buat kelas dari penugasan mengajar yang sudah disiapkan pada Phase 04.</p></Card>}
 </AppShell>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">{label}</span>{children}</label>}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <Card className="p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700">{icon}</div><p className="mt-4 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></Card>}
function Mini({icon,n,label}:{icon:React.ReactNode;n:number;label:string}){return <div className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-slate-500">{icon}<span className="text-[10px]">{label}</span></div><b className="mt-2 block text-lg">{n}</b></div>}
