import { useEffect, useMemo, useState } from 'react'
import { CalendarClock, CheckCircle2, ClipboardList, Eye, FileCheck2, Plus, UsersRound } from 'lucide-react'
import { Link } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { Badge, Button, Card } from '@/components/ui'
import { assignmentApi, type Assignment } from '@/features/assignment/api'
import { classroomApi, type Classroom } from '@/features/classroom/api'

export default function TeacherAssignments(){
 const[items,setItems]=useState<Assignment[]>([]),[classes,setClasses]=useState<Classroom[]>([]),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const[form,setForm]=useState({classroom_id:0,title:'',instructions:'',due_at:''})
 async function load(){setLoading(true);setError('');try{const[a,b]=await Promise.all([assignmentApi.teacher.list(),classroomApi.teacher.list()]);setItems(a.data);setClasses(b.data.filter(x=>x.status==='published'))}catch(e){setError(e instanceof Error?e.message:'Gagal memuat penugasan.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function create(){if(!form.classroom_id||!form.title.trim())return;setSaving(true);try{await assignmentApi.teacher.create(form.classroom_id,{title:form.title,instructions:form.instructions,due_at:form.due_at?new Date(form.due_at).toISOString():null});setShow(false);setForm({classroom_id:0,title:'',instructions:'',due_at:''});await load()}catch(e){setError(e instanceof Error?e.message:'Gagal membuat tugas.')}finally{setSaving(false)}}
 const review=useMemo(()=>items.reduce((n,x)=>n+(x.pending_review_count??0),0),[items])
 return <AppShell title="Penugasan"><PageHeader eyebrow="Assignment & Submission • Phase 06" title="Assignment Center" description="Buat tugas, atur deadline dan rubrik, lalu review submission siswa dari satu workspace." action={<Button onClick={()=>setShow(v=>!v)}><Plus size={16}/>{show?'Tutup':'Buat tugas'}</Button>}/>
 {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
 {show&&<Card className="mb-6 p-5"><div className="grid gap-4 lg:grid-cols-2"><Field label="Kelas digital"><select value={form.classroom_id} onChange={e=>setForm(v=>({...v,classroom_id:Number(e.target.value)}))} className="h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value={0}>Pilih kelas</option>{classes.map(c=><option key={c.id} value={c.id}>{c.title} • {c.teaching_assignment?.class_group?.name}</option>)}</select></Field><Field label="Judul tugas"><input value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Contoh: Tugas 01 — Exposure Triangle"/></Field><Field label="Deadline"><input type="datetime-local" value={form.due_at} onChange={e=>setForm(v=>({...v,due_at:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"/></Field><Field label="Instruksi singkat"><input value={form.instructions} onChange={e=>setForm(v=>({...v,instructions:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Brief tugas..."/></Field></div><div className="mt-4 flex justify-end"><Button disabled={saving} onClick={create}>{saving?'Menyimpan...':'Buat sebagai draft'}</Button></div></Card>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<ClipboardList/>} n={items.length} label="Total tugas"/><Stat icon={<CheckCircle2/>} n={items.filter(x=>x.status==='published').length} label="Published"/><Stat icon={<FileCheck2/>} n={review} label="Perlu direview"/><Stat icon={<UsersRound/>} n={items.reduce((n,x)=>n+(x.submissions_count??0),0)} label="Submission"/></div>
 <div className="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{loading?[1,2,3].map(i=><Card key={i} className="h-56 animate-pulse bg-slate-100"/>):items.map(a=><Card key={a.id} className="p-5"><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700"><ClipboardList size={18}/></div><Badge tone={a.status==='published'?'green':'amber'}>{a.status}</Badge></div><h3 className="mt-5 text-base font-semibold text-slate-950">{a.title}</h3><p className="mt-1 text-xs text-slate-500">{a.classroom?.title} • {a.classroom?.teaching_assignment?.class_group?.name}</p><div className="mt-5 grid grid-cols-2 gap-3"><Mini label="Submission" n={a.submissions_count??0}/><Mini label="Perlu review" n={a.pending_review_count??0}/></div><div className="mt-4 flex items-center gap-2 text-xs text-slate-500"><CalendarClock size={14}/>{a.due_at?formatDate(a.due_at):'Tanpa deadline'}</div><Link to={`/teacher/assignments/${a.id}`}><Button variant="dark" className="mt-4 w-full"><Eye size={15}/>Kelola & review</Button></Link></Card>)}</div>
 </AppShell>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-1.5 block text-[11px] font-semibold text-slate-500">{label}</span>{children}</label>}
function Stat({icon,n,label}:{icon:React.ReactNode;n:number;label:string}){return <Card className="p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-blue-50 text-blue-700">{icon}</div><p className="mt-4 text-2xl font-semibold">{n}</p><p className="mt-1 text-xs text-slate-500">{label}</p></Card>}
function Mini({label,n}:{label:string;n:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] text-slate-500">{label}</p><b className="mt-1 block text-lg">{n}</b></div>}
function formatDate(v:string){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}
