import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { BookOpen, CheckCircle2, ClipboardCheck, MessageSquareText, Plus, UsersRound } from 'lucide-react'
import { Link } from 'react-router'
import AppShell from '@/components/layout/AppShell'
import { PageHeader } from '@/components/shared/PageHeader'
import { SectionTitle } from '@/components/shared/SectionTitle'
import { Badge, Button, Card } from '@/components/ui'
import { classroomApi, type Classroom } from '@/features/classroom/api'

export default function TeacherDashboard(){const [classes,setClasses]=useState<Classroom[]>([]);useEffect(()=>{classroomApi.teacher.list().then(r=>setClasses(r.data)).catch(()=>{})},[]);const published=useMemo(()=>classes.filter(x=>x.status==='published').length,[classes]);const materials=useMemo(()=>classes.reduce((n,x)=>n+(x.materials_count??0),0),[classes]);return <AppShell title="Ringkasan Guru"><PageHeader eyebrow="EduNova • Digital Classroom" title="Selamat datang, Pak Susanto." description="Kelola kelas digital, susun materi, dan pantau kesiapan konten untuk siswa." action={<Link to="/teacher/classrooms"><Button><Plus size={16}/>Kelola kelas</Button></Link>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<BookOpen/>} n={String(classes.length)} t="Kelas digital" note={`${published} published`}/><Stat icon={<CheckCircle2/>} n={String(materials)} t="Materi dibuat" note="Phase 05"/><Stat icon={<ClipboardCheck/>} n="0" t="Perlu dinilai" note="Phase 06"/><Stat icon={<MessageSquareText/>} n="0" t="Diskusi baru" note="Segera hadir"/></div><div className="mt-7 grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="p-5"><SectionTitle eyebrow="Digital classroom" title="Kelas yang Anda kelola"/><div className="overflow-hidden rounded-xl border border-slate-100">{classes.length?classes.slice(0,4).map((c,i)=><div className={`grid items-center gap-4 px-4 py-4 sm:grid-cols-[1fr_auto] ${i?'border-t border-slate-100':''}`} key={c.id}><div><div className="flex flex-wrap items-center gap-2"><b className="text-sm font-semibold text-slate-800">{c.title}</b><Badge tone={c.status==='published'?'green':'amber'}>{c.status}</Badge></div><p className="mt-1 text-xs text-slate-400">{c.teaching_assignment?.class_group?.name} • {c.materials_count??0} materi</p></div><Link to={`/teacher/classrooms/${c.id}`}><Button variant="dark" size="sm">Buka builder</Button></Link></div>):<div className="p-6 text-center text-xs text-slate-500">Belum ada kelas digital.</div>}</div></Card><Card className="p-5"><SectionTitle eyebrow="Next step" title="Workflow guru"/><div className="space-y-3">{[['1','Buat chapter','Susun topik belajar'],['2','Tambah materi','Teks, video, PDF, link'],['3','Publish','Buka untuk siswa']].map(([n,t,d])=><div key={n} className="flex gap-3 rounded-xl border border-slate-100 p-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-blue-50 text-xs font-bold text-blue-700">{n}</div><div><p className="text-sm font-semibold">{t}</p><p className="mt-1 text-xs text-slate-500">{d}</p></div></div>)}</div></Card></div></AppShell>}
function Stat({icon,n,t,note}:{icon:ReactNode,n:string,t:string,note:string}){return <Card className="p-5"><div className="flex items-start justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-slate-50 text-slate-600">{icon}</div><span className="text-[11px] text-slate-400">{note}</span></div><p className="mt-5 text-2xl font-semibold tracking-tight">{n}</p><p className="mt-1 text-xs text-slate-500">{t}</p></Card>}
