import { apiRequest, ensureCsrfCookie } from '@/lib/api/client'
export type QuizOption={id:number;option_text:string;is_correct?:boolean;position?:number}
export type BankItem={id:number;type:'multiple_choice'|'true_false'|'essay';question:string;explanation?:string|null;default_points:number;options?:QuizOption[]}
export type QuizQuestion={id:number;quiz_id:number;question_bank_item_id:number;points:number;position:number;bank_item?:BankItem;bankItem?:BankItem}
export type AttemptSummary={id:number;attempt_no:number;status:string;started_at:string;expires_at?:string|null;submitted_at?:string|null;total_score?:number|null;auto_submitted?:boolean;student?:{id:number;name:string;username:string;subtitle?:string|null}}
export type Quiz={id:number;classroom_id:number;title:string;description?:string|null;instructions?:string|null;opens_at?:string|null;closes_at?:string|null;time_limit_minutes:number;max_attempts:number;shuffle_questions:boolean;shuffle_options:boolean;passing_score:number;result_policy:'immediately'|'after_close'|'manual';status:'draft'|'published';questions_count?:number;attempts_count?:number;pending_review_count?:number;attempts_used?:number;best_score?:number|null;active_attempt_id?:number|null;attempt_history?:AttemptSummary[];questions?:QuizQuestion[];classroom?:{id:number;title:string;teaching_assignment?:{subject?:{id:number;code:string;name:string};class_group?:{id:number;name:string};teacher?:{id:number;name:string}}}}
export type AttemptQuestion={id:number;type:'multiple_choice'|'true_false'|'essay';question:string;points:number;options:QuizOption[];answer?:{selected_option_id?:number|null;boolean_answer?:boolean|null;text_answer?:string|null}|null}
export type QuizAttempt={id:number;attempt_no:number;status:string;started_at:string;expires_at?:string|null;quiz:{id:number;title:string;instructions?:string|null;time_limit_minutes:number};questions:AttemptQuestion[]}
export type QuizResult={id:number;attempt_no:number;status:string;submitted_at?:string|null;auto_submitted:boolean;objective_score:number;essay_score:number;total_score?:number|null;max_score:number;percentage?:number|null;passed?:boolean|null;result_visible:boolean;quiz:{id:number;title:string;passing_score:number;result_policy:string};answers?:Array<{quiz_question_id:number;question:string;type:string;awarded_points?:number|null;max_points:number;is_correct?:boolean|null;teacher_feedback?:string|null;explanation?:string|null}>}
export type TeacherAttempt={id:number;quiz_id:number;attempt_no:number;status:string;started_at:string;submitted_at?:string|null;auto_submitted:boolean;objective_score:number;essay_score:number;total_score?:number|null;max_score:number;student:{id:number;name:string;username:string;subtitle?:string|null};answers:Array<{id:number;quiz_question_id:number;type:string;question:string;text_answer?:string|null;selected_option_id?:number|null;boolean_answer?:boolean|null;awarded_points?:number|null;max_points:number;teacher_feedback?:string|null}>}
type Data<T>={data:T}
async function json<T>(path:string,method:string,body?:unknown){await ensureCsrfCookie();return apiRequest<Data<T>>(path,{method,body:body?JSON.stringify(body):undefined})}
export const quizApi={teacher:{list:()=>apiRequest<Data<Quiz[]>>('/teacher/quizzes'),get:(id:number)=>apiRequest<Data<Quiz>>(`/teacher/quizzes/${id}`),create:(classroomId:number,body:Partial<Quiz>)=>json<Quiz>(`/teacher/classrooms/${classroomId}/quizzes`,'POST',body),update:(id:number,body:Partial<Quiz>)=>json<Quiz>(`/teacher/quizzes/${id}`,'PUT',body),publish:(id:number,published:boolean)=>json<Quiz>(`/teacher/quizzes/${id}/publish`,'POST',{published}),remove:async(id:number)=>{await ensureCsrfCookie();return apiRequest(`/teacher/quizzes/${id}`,{method:'DELETE'})},bank:()=>apiRequest<Data<BankItem[]>>('/teacher/question-bank'),createQuestion:(quizId:number,body:{type:string;question:string;explanation?:string;default_points:number;options?:Array<{option_text:string;is_correct:boolean}>})=>json<QuizQuestion>(`/teacher/quizzes/${quizId}/questions`,'POST',body),addFromBank:(quizId:number,questionBankItemId:number,points?:number)=>json<QuizQuestion>(`/teacher/quizzes/${quizId}/questions/from-bank`,'POST',{question_bank_item_id:questionBankItemId,points}),removeQuestion:async(quizId:number,questionId:number)=>{await ensureCsrfCookie();return apiRequest(`/teacher/quizzes/${quizId}/questions/${questionId}`,{method:'DELETE'})},attempts:(quizId:number)=>apiRequest<Data<AttemptSummary[]>>(`/teacher/quizzes/${quizId}/attempts`),attempt:(id:number)=>apiRequest<Data<TeacherAttempt>>(`/teacher/quiz-attempts/${id}`),grade:(id:number,answers:Array<{quiz_question_id:number;awarded_points:number;teacher_feedback?:string}>)=>json<TeacherAttempt>(`/teacher/quiz-attempts/${id}/grade`,'POST',{answers}),release:(quizId:number)=>json<Quiz>(`/teacher/quizzes/${quizId}/release-results`,'POST',{})},student:{list:()=>apiRequest<Data<Quiz[]>>('/student/quizzes'),get:(id:number)=>apiRequest<Data<Quiz>>(`/student/quizzes/${id}`),start:(id:number)=>json<QuizAttempt>(`/student/quizzes/${id}/start`,'POST',{}),attempt:(id:number)=>apiRequest<Data<QuizAttempt>>(`/student/quiz-attempts/${id}`),saveAnswer:(id:number,body:{quiz_question_id:number;selected_option_id?:number|null;boolean_answer?:boolean|null;text_answer?:string|null})=>json(`/student/quiz-attempts/${id}/answer`,'POST',body),submit:(id:number)=>json<QuizResult>(`/student/quiz-attempts/${id}/submit`,'POST',{}),result:(id:number)=>apiRequest<Data<QuizResult>>(`/student/quiz-attempts/${id}/result`)}}
