<?php
namespace App\Http\Controllers\Api\V1\Student;
use App\Http\Controllers\Controller; use App\Models\ClassEnrollment; use App\Models\QuestionBankOption; use App\Models\Quiz; use App\Models\QuizAnswer; use App\Models\QuizAttempt; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class QuizController extends Controller {
 private function available(Request $r){$classIds=ClassEnrollment::where('student_id',$r->user()->id)->where('status','active')->pluck('class_group_id');return Quiz::query()->where('status','published')->whereHas('classroom',fn($q)=>$q->where('school_id',$r->user()->school_id)->whereHas('teachingAssignment',fn($t)=>$t->whereIn('class_group_id',$classIds)));}
 public function index(Request $r):JsonResponse{$items=$this->available($r)->with(['classroom.teachingAssignment.subject:id,code,name','classroom.teachingAssignment.teacher:id,name'])->withCount('questions')->latest()->get()->map(function($q)use($r){$q->attempts_used=$q->attempts()->where('student_id',$r->user()->id)->count();$q->best_score=$q->attempts()->where('student_id',$r->user()->id)->whereNotNull('total_score')->max('total_score');$q->active_attempt_id=$q->attempts()->where('student_id',$r->user()->id)->where('status','in_progress')->value('id');return $q;});return response()->json(['data'=>$items]);}
 public function show(Request $r,int $id):JsonResponse{$q=$this->available($r)->with(['classroom.teachingAssignment.subject:id,code,name'])->withCount('questions')->findOrFail($id);$attempts=$q->attempts()->where('student_id',$r->user()->id)->latest('attempt_no')->get(['id','attempt_no','status','started_at','submitted_at','expires_at','total_score','auto_submitted']);$q->attempts_used=$attempts->count();$q->attempt_history=$attempts;return response()->json(['data'=>$q]);}
 public function start(Request $r,int $id):JsonResponse{$q=$this->available($r)->with('questions.bankItem.options')->findOrFail($id);if($q->opens_at&&now()->lt($q->opens_at))return response()->json(['message'=>'Quiz belum dibuka.'],422);if($q->closes_at&&now()->gt($q->closes_at))return response()->json(['message'=>'Quiz sudah ditutup.'],422);$active=$q->attempts()->where('student_id',$r->user()->id)->where('status','in_progress')->latest()->first();if($active){$this->expireIfNeeded($active);if($active->fresh()->status==='in_progress')return response()->json(['data'=>$this->attemptPayload($active->fresh(),false)]);}$count=$q->attempts()->where('student_id',$r->user()->id)->count();if($count>=$q->max_attempts)return response()->json(['message'=>'Batas attempt sudah tercapai.'],422);$ids=$q->questions->pluck('id')->all();if($q->shuffle_questions)shuffle($ids);$optionOrder=[];foreach($q->questions as $qq){$opts=$qq->bankItem->options->pluck('id')->all();if($q->shuffle_options)shuffle($opts);$optionOrder[(string)$qq->id]=$opts;}$expires=now()->addMinutes($q->time_limit_minutes);if($q->closes_at&&$expires->gt($q->closes_at))$expires=$q->closes_at->copy();$a=QuizAttempt::create(['quiz_id'=>$q->id,'student_id'=>$r->user()->id,'attempt_no'=>$count+1,'status'=>'in_progress','started_at'=>now(),'expires_at'=>$expires,'question_order'=>$ids,'option_order'=>$optionOrder]);return response()->json(['data'=>$this->attemptPayload($a,false)],201);}
 public function attempt(Request $r,int $attemptId):JsonResponse{$a=QuizAttempt::where('student_id',$r->user()->id)->with('quiz')->findOrFail($attemptId);$this->expireIfNeeded($a);$a=$a->fresh();if($a->status!=='in_progress')return response()->json(['message'=>'Attempt sudah selesai.','data'=>['id'=>$a->id,'status'=>$a->status]],409);return response()->json(['data'=>$this->attemptPayload($a,false)]);}
 public function saveAnswer(Request $r,int $attemptId):JsonResponse{$a=QuizAttempt::where('student_id',$r->user()->id)->with('quiz.questions.bankItem.options')->findOrFail($attemptId);$this->expireIfNeeded($a);if($a->fresh()->status!=='in_progress')return response()->json(['message'=>'Waktu quiz telah berakhir.'],422);$d=$r->validate(['quiz_question_id'=>'required|integer','selected_option_id'=>'nullable|integer','boolean_answer'=>'nullable|boolean','text_answer'=>'nullable|string|max:20000']);$qq=$a->quiz->questions->firstWhere('id',(int)$d['quiz_question_id']);if(!$qq)return response()->json(['message'=>'Soal tidak valid.'],422);$answer=QuizAnswer::updateOrCreate(['quiz_attempt_id'=>$a->id,'quiz_question_id'=>$qq->id],['selected_option_id'=>$d['selected_option_id']??null,'boolean_answer'=>$d['boolean_answer']??null,'text_answer'=>$d['text_answer']??null,'saved_at'=>now()]);return response()->json(['data'=>$answer]);}
 public function submit(Request $r,int $attemptId):JsonResponse{$a=QuizAttempt::where('student_id',$r->user()->id)->with('quiz.questions.bankItem.options')->findOrFail($attemptId);if($a->status!=='in_progress')return response()->json(['data'=>$this->resultPayload($a)]);$this->finalize($a,false);return response()->json(['data'=>$this->resultPayload($a->fresh())]);}
 public function result(Request $r,int $attemptId):JsonResponse{$a=QuizAttempt::where('student_id',$r->user()->id)->with('quiz')->findOrFail($attemptId);if($a->status==='in_progress')return response()->json(['message'=>'Attempt belum disubmit.'],422);if(!$this->canSeeResult($a))return response()->json(['message'=>'Hasil belum tersedia sesuai kebijakan guru.','data'=>['id'=>$a->id,'status'=>$a->status,'result_visible'=>false]],403);return response()->json(['data'=>$this->resultPayload($a)]);}
 private function expireIfNeeded(QuizAttempt $a):void{if($a->status==='in_progress'&&$a->expires_at&&now()->gte($a->expires_at))$this->finalize($a,true);}
 private function finalize(QuizAttempt $a,bool $auto):void{DB::transaction(function()use($a,$auto){$a->load('quiz.questions.bankItem.options');$objective=0;$hasEssay=false;foreach($a->quiz->questions as $qq){$item=$qq->bankItem;$ans=QuizAnswer::firstOrCreate(['quiz_attempt_id'=>$a->id,'quiz_question_id'=>$qq->id]);if($item->type==='essay'){$hasEssay=true;continue;}$correct=false;if($item->type==='multiple_choice'){$opt=$item->options->firstWhere('id',$ans->selected_option_id);$correct=(bool)($opt?->is_correct);}else{$correctOpt=$item->options->firstWhere('is_correct',true);$expected=$correctOpt?->option_text==='Benar';$correct=$ans->boolean_answer!==null&&$ans->boolean_answer===$expected;}$points=$correct?(float)$qq->points:0;$objective+=$points;$ans->update(['is_correct'=>$correct,'awarded_points'=>$points]);}$a->update(['status'=>$hasEssay?'submitted':'graded','submitted_at'=>now(),'auto_submitted'=>$auto,'objective_score'=>$objective,'essay_score'=>0,'total_score'=>$hasEssay?null:$objective,'graded_at'=>$hasEssay?null:now()]);});}
 private function attemptPayload(QuizAttempt $a,bool $answers):array{$a->load('quiz.questions.bankItem.options','answers');$byId=$a->quiz->questions->keyBy('id');$ordered=collect($a->question_order?:$byId->keys()->all())->map(fn($id)=>$byId->get($id))->filter()->values()->map(function($qq)use($a,$answers){$item=$qq->bankItem;$opts=$item->options->keyBy('id');$order=$a->option_order[(string)$qq->id]??$opts->keys()->all();$optionData=collect($order)->map(fn($id)=>$opts->get($id))->filter()->values()->map(fn($o)=>['id'=>$o->id,'option_text'=>$o->option_text])->all();$ans=$a->answers->firstWhere('quiz_question_id',$qq->id);return['id'=>$qq->id,'type'=>$item->type,'question'=>$item->question,'points'=>(float)$qq->points,'options'=>$optionData,'answer'=>$ans?['selected_option_id'=>$ans->selected_option_id,'boolean_answer'=>$ans->boolean_answer,'text_answer'=>$ans->text_answer]:null];})->all();return['id'=>$a->id,'attempt_no'=>$a->attempt_no,'status'=>$a->status,'started_at'=>$a->started_at,'expires_at'=>$a->expires_at,'quiz'=>['id'=>$a->quiz->id,'title'=>$a->quiz->title,'instructions'=>$a->quiz->instructions,'time_limit_minutes'=>$a->quiz->time_limit_minutes],'questions'=>$ordered];}
 private function canSeeResult(QuizAttempt $a):bool{$p=$a->quiz->result_policy;if($p==='immediately')return $a->status==='graded';if($p==='after_close')return $a->status==='graded'&&(!$a->quiz->closes_at||now()->gte($a->quiz->closes_at));return false;}
 private function resultPayload(QuizAttempt $a):array{$a->load('quiz.questions.bankItem.options','answers.quizQuestion.bankItem.options');$visible=$this->canSeeResult($a);$max=(float)$a->quiz->questions()->sum('points');$pct=$max>0&&$a->total_score!==null?round(((float)$a->total_score/$max)*100,2):null;return['id'=>$a->id,'attempt_no'=>$a->attempt_no,'status'=>$a->status,'submitted_at'=>$a->submitted_at,'auto_submitted'=>$a->auto_submitted,'objective_score'=>(float)$a->objective_score,'essay_score'=>(float)$a->essay_score,'total_score'=>$a->total_score!==null?(float)$a->total_score:null,'max_score'=>$max,'percentage'=>$pct,'passed'=>$pct!==null?$pct>=(float)$a->quiz->passing_score:null,'result_visible'=>$visible,'quiz'=>['id'=>$a->quiz->id,'title'=>$a->quiz->title,'passing_score'=>(float)$a->quiz->passing_score,'result_policy'=>$a->quiz->result_policy],'answers'=>$visible?$a->answers->map(function($ans){$qq=$ans->quizQuestion;$item=$qq->bankItem;return['quiz_question_id'=>$qq->id,'question'=>$item->question,'type'=>$item->type,'awarded_points'=>$ans->awarded_points!==null?(float)$ans->awarded_points:null,'max_points'=>(float)$qq->points,'is_correct'=>$ans->is_correct,'teacher_feedback'=>$ans->teacher_feedback,'explanation'=>$item->explanation];})->values():[]];}
}
